import { createClient } from "npm:@supabase/supabase-js@2";
const PASSWORD_HASH="67541863bd267f78446b60b489625bdd452dca1bd003fa1e620dd98de2fb6c6d";
const ORIGIN="https://aqoon.live";
const FORM_VERSION="phone-first-v2-multineed";
const H=()=>({"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type, x-tracker-password, authorization","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("");}
function clean(v:unknown,max:number){return typeof v==="string"?v.trim().slice(0,max):"";}
function additional(v:unknown){if(!Array.isArray(v))return [];const out:any[]=[];const seen=new Set<string>();for(const x of v.slice(0,3)){if(!x||typeof x!=="object")continue;const main=clean((x as any).main_need,100),sub=clean((x as any).sub_need,300),age=clean((x as any).age_group,50)||null;if(!main||!sub||seen.has(main))continue;seen.add(main);out.push({main_need:main,sub_need:sub,age_group:age});}return out;}
Deno.serve(async(req)=>{const h=H();if(req.method==="OPTIONS")return new Response(null,{status:204,headers:h});if(req.method!=="POST")return new Response(JSON.stringify({error:"method_not_allowed"}),{status:405,headers:h});
const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return new Response(JSON.stringify({error:"server_config"}),{status:500,headers:h});
const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
const p=req.headers.get("x-tracker-password")||"";const passwordOk=!!p&&(await sha(p))===PASSWORD_HASH;let jwtOperatorId:string|null=null;
if(!passwordOk){const authHeader=req.headers.get("authorization")||"";const m=authHeader.match(/^Bearer\s+(.+)$/i);if(m){const{data,error}=await db.auth.getUser(m[1]);if(!error&&data?.user){const{data:op}=await db.from("operators").select("id").eq("auth_user_id",data.user.id).maybeSingle();if(op)jwtOperatorId=op.id;}}}
if(!passwordOk&&!jwtOperatorId)return new Response(JSON.stringify({error:"unauthorized"}),{status:401,headers:h});
let b:any={};try{b=await req.json()}catch{};const action=String(b.action||"");
if(action==="list"){const{data,error}=await db.from("family_intake_contacts").select("id,created_at,updated_at,request_id,name,phone,city,main_need,sub_need,age_group,additional_needs,completed,assigned_operator_id,last_call_outcome,last_call_at,last_call_next_follow_up_at,last_call_notes").eq("completed",false).order("created_at",{ascending:false}).limit(500);if(error)return new Response(JSON.stringify({error:"db_error",detail:error.message}),{status:500,headers:h});return new Response(JSON.stringify({contacts:data||[]}),{headers:h});}
if(action==="assign"){const id=clean(b.id,80);if(!id)return new Response(JSON.stringify({error:"missing_id"}),{status:400,headers:h});const operatorId=jwtOperatorId||(typeof b.operator_id==="string"&&b.operator_id.trim()?b.operator_id.trim():null);if(!operatorId)return new Response(JSON.stringify({error:"missing_operator"}),{status:400,headers:h});const{data,error}=await db.from("family_intake_contacts").update({assigned_operator_id:operatorId,updated_at:new Date().toISOString()}).eq("id",id).eq("completed",false).select("id,assigned_operator_id").maybeSingle();if(error)return new Response(JSON.stringify({error:"db_error",detail:error.message}),{status:500,headers:h});if(!data)return new Response(JSON.stringify({error:"not_found_or_completed"}),{status:404,headers:h});return new Response(JSON.stringify({ok:true,contact:data}),{headers:h});}
if(action==="delete"){const id=clean(b.id,80);if(!id)return new Response(JSON.stringify({error:"missing_id"}),{status:400,headers:h});const{data,error}=await db.from("family_intake_contacts").delete().eq("id",id).eq("completed",false).select("id").maybeSingle();if(error)return new Response(JSON.stringify({error:"db_error",detail:error.message}),{status:500,headers:h});if(!data)return new Response(JSON.stringify({error:"not_found_or_completed"}),{status:404,headers:h});return new Response(JSON.stringify({ok:true}),{headers:h});}
// A call attempt against a still-incomplete intake must never create a
// family_leads row by itself - only finishing the intake form (below) does
// that. This just records the outcome (reached/no_answer/busy/call_later)
// on the partial contact, so an operator who only gets "no answer" sees
// that reflected without the case silently jumping to First Contact with
// invented "Not asked yet" facts.
if(action==="log_call"){const id=clean(b.id,80),outcome=String(b.call_outcome||"");if(!id)return new Response(JSON.stringify({error:"missing_id"}),{status:400,headers:h});if(!["reached","no_answer","call_later","busy"].includes(outcome))return new Response(JSON.stringify({error:"invalid_call_outcome"}),{status:400,headers:h});let follow:string|null=null;if(outcome==="no_answer")follow=new Date(Date.now()+86400000).toISOString();else if(outcome==="call_later"||outcome==="busy"){const d=new Date(b.next_follow_up_at||"");if(Number.isNaN(d.getTime())||d.getTime()<=Date.now())return new Response(JSON.stringify({error:"future_follow_up_required"}),{status:400,headers:h});follow=d.toISOString();}const operatorId=jwtOperatorId||(typeof b.operator_id==="string"&&b.operator_id.trim()?b.operator_id.trim():null),now=new Date().toISOString();const patch:any={last_call_outcome:outcome,last_call_at:now,last_call_next_follow_up_at:follow,last_call_notes:clean(b.notes,1000)||null,updated_at:now};if(operatorId)patch.assigned_operator_id=operatorId;const{data,error}=await db.from("family_intake_contacts").update(patch).eq("id",id).eq("completed",false).select("id,last_call_outcome,last_call_at,last_call_next_follow_up_at,last_call_notes,assigned_operator_id").maybeSingle();if(error)return new Response(JSON.stringify({error:"db_error",detail:error.message}),{status:500,headers:h});if(!data)return new Response(JSON.stringify({error:"not_found_or_completed"}),{status:404,headers:h});return new Response(JSON.stringify({ok:true,contact:data}),{headers:h});}
if(action==="complete"){const id=clean(b.id,80),city=clean(b.city,100),main=clean(b.main_need,100),sub=clean(b.sub_need,300),age=clean(b.age_group,50)||null,extras=additional(b.additional_needs);if(!id||!city||!main||!sub)return new Response(JSON.stringify({error:"missing_fields"}),{status:400,headers:h});const{data:contact,error:ce}=await db.from("family_intake_contacts").select("id,request_id,name,phone,referrer_host,utm_source,utm_medium,utm_campaign,form_version,assigned_operator_id,last_call_outcome,last_call_at,last_call_next_follow_up_at,last_call_notes").eq("id",id).eq("completed",false).maybeSingle();if(ce)return new Response(JSON.stringify({error:"db_error",detail:ce.message}),{status:500,headers:h});if(!contact)return new Response(JSON.stringify({error:"not_found_or_completed"}),{status:404,headers:h});const now=new Date().toISOString();const existing=await db.from("family_leads").select("id").eq("intake_request_id",contact.request_id).maybeSingle();let leadId:string;if(existing.data?.id){leadId=existing.data.id;const{error}=await db.from("family_leads").update({name:contact.name,phone:contact.phone,city,main_need:main,sub_need:sub,age_group:age,additional_needs:extras,form_version:FORM_VERSION,updated_at:now}).eq("id",leadId);if(error)return new Response(JSON.stringify({error:"db_error",detail:error.message}),{status:500,headers:h});}else{const tier=main==="Carruur iyo skuul"?1:2;const{data:lead,error}=await db.from("family_leads").insert({name:contact.name,phone:contact.phone,city,main_need:main,sub_need:sub,age_group:age,additional_needs:extras,tier,status:"new",source:"operator-completed-intake",lang:"so",form_version:FORM_VERSION,intake_request_id:contact.request_id,assigned_operator_id:contact.assigned_operator_id||null,referrer_host:contact.referrer_host||null,utm_source:contact.utm_source||null,utm_medium:contact.utm_medium||null,utm_campaign:contact.utm_campaign||null}).select("id").single();if(error)return new Response(JSON.stringify({error:"db_error",detail:error.message}),{status:500,headers:h});leadId=lead.id;}
// A call may already have been logged against the intake before it was
// finished (e.g. the family answered, then the operator filled in the
// form right there on the call) - carry that one outcome forward into the
// lead's real call history instead of losing it once the partial row
// stops being shown.
if(contact.last_call_outcome){const{error:callError}=await db.from("family_call_log").insert({family_lead_id:leadId,operator_id:contact.assigned_operator_id||null,outcome:contact.last_call_outcome,next_follow_up_at:contact.last_call_next_follow_up_at,notes:contact.last_call_notes});if(callError)return new Response(JSON.stringify({error:"call_history_write_failed",detail:callError.message}),{status:500,headers:h});const{error:leadCallError}=await db.from("family_leads").update({last_call_outcome:contact.last_call_outcome,last_call_at:contact.last_call_at}).eq("id",leadId);if(leadCallError)return new Response(JSON.stringify({error:"lead_call_sync_failed",detail:leadCallError.message}),{status:500,headers:h});}
const{error:ue}=await db.from("family_intake_contacts").update({completed:true,city,main_need:main,sub_need:sub,age_group:age,additional_needs:extras,form_version:FORM_VERSION,updated_at:now}).eq("id",id);if(ue)return new Response(JSON.stringify({error:"db_error",detail:ue.message}),{status:500,headers:h});return new Response(JSON.stringify({ok:true,lead_id:leadId}),{headers:h});}
return new Response(JSON.stringify({error:"unknown_action"}),{status:400,headers:h});});
