import { createClient } from "npm:@supabase/supabase-js@2";
const ORIGIN="https://aqoon.live";
const DEFAULT_VERSION="phone-first-v1";
const VERSIONS=new Set(["phone-first-v1","phone-first-v2-multineed"]);
const EVENTS=new Set(["page_view","start","city_selected","need_selected","age_selected","sub_selected","contact_view","contact_started","submit_attempt","validation_error","submit_error","more_help_view","additional_need_started","additional_need_added","send_request","analytics_consent"]);
function headers(){return {"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};}
function clean(v:unknown,max:number){return typeof v==="string"?v.trim().slice(0,max):"";}
function isUuid(v:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);}
function device(ua:string){ua=ua.toLowerCase();if(/ipad|tablet/.test(ua))return"tablet";if(/mobi|iphone|android/.test(ua))return"mobile";return"desktop";}
Deno.serve(async(req)=>{const h=headers();if(req.method==="OPTIONS")return new Response(null,{status:204,headers:h});if(req.method!=="POST")return new Response(JSON.stringify({error:"method_not_allowed"}),{status:405,headers:h});let body:any={};try{body=await req.json()}catch{return new Response(JSON.stringify({error:"invalid_json"}),{status:400,headers:h})}
 const eventName=clean(body.event_name,40),sessionId=clean(body.session_id,50),visitorId=clean(body.visitor_id,50),eventId=clean(body.event_id,50),formVersion=clean(body.form_version,40)||DEFAULT_VERSION;
 if(!EVENTS.has(eventName)||!isUuid(sessionId)||!isUuid(visitorId)||!isUuid(eventId)||!VERSIONS.has(formVersion))return new Response(JSON.stringify({error:"invalid_event"}),{status:400,headers:h});
 const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return new Response(JSON.stringify({error:"server_config"}),{status:500,headers:h});const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const row={event_id:eventId,visitor_id:visitorId,session_id:sessionId,event_name:eventName,form_version:formVersion,path:clean(body.path,100)||"/caawi",screen:clean(body.screen,40)||null,city:clean(body.city,100)||null,main_need:clean(body.main_need,100)||null,sub_need:clean(body.sub_need,200)||null,age_group:clean(body.age_group,50)||null,referrer_host:clean(body.referrer_host,200)||null,utm_source:clean(body.utm_source,100)||null,utm_medium:clean(body.utm_medium,100)||null,utm_campaign:clean(body.utm_campaign,150)||null,device_type:device(req.headers.get("user-agent")||"")};
 const {error}=await db.from("family_funnel_events").insert(row);if(error&&error.code!=="23505")return new Response(JSON.stringify({error:"db_error"}),{status:500,headers:h});return new Response(JSON.stringify({ok:true}),{status:200,headers:h});});
