(function(global){'use strict';
function normalizeFinnishPhone(v){var raw=String(v||'').trim().replace(/[\s().-]/g,'');if(!raw)return'';if(raw.indexOf('+')>0||((raw.match(/\+/g)||[]).length>1))return'';if(raw.indexOf('00358')===0)raw='+358'+raw.slice(5);else if(raw.indexOf('358')===0)raw='+358'+raw.slice(3);if(raw.indexOf('+358')===0){if(!/^\+358\d+$/.test(raw))return'';var n=raw.slice(4);if(n.indexOf('0')===0)n=n.slice(1);if(!/^[1-9]\d{6,9}$/.test(n))return'';return'+358'+n}if(!/^\d+$/.test(raw))return'';if(/^0\d{7,10}$/.test(raw))return'+358'+raw.slice(1);return''}
function pathForNeed(mainNeed){return mainNeed==='kids'?['contact','city','need','age','explain','sub']:['contact','city','need','explain','sub']}
function bucketForNeed(mainNeed,age){return mainNeed==='kids'?(age==='under7'?'daycare':'hobby'):mainNeed}
function nextAfterNeed(mainNeed){return mainNeed==='kids'?'age':'explain'}
function nextAfterContactSaved(){return'city'}
function nextAfterSubmitSuccess(){return'confirm'}
function shouldWarnOnExit(exitGuard,screen){return!!exitGuard&&screen!=='hero'&&screen!=='confirm'}
function createSubmitGate(){var locked=false;return{enter:function(){if(locked)return false;locked=true;return true},release:function(){locked=false},isLocked:function(){return locked}}}
function buildContactPayload(state,ids,attribution,website){return Object.assign({request_id:ids.requestId,visitor_id:ids.visitor,session_id:ids.session,name:state.name,phone:state.phone,website:website||''},attribution||{})}
function buildSubmitPayload(state,ids,attribution,city,mainNeedLabel){return Object.assign({request_id:ids.requestId,visitor_id:ids.visitor,session_id:ids.session,lang:'so',name:state.name,phone:state.phone,city:city,main_need:mainNeedLabel,sub_need:state.subNeed,age_group:state.age||null,website:''},attribution||{})}
function postJson(fetchImpl,url,payload){return fetchImpl(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(function(r){return r.json().catch(function(){return{}}).then(function(d){if(!r.ok){var x=Error(d.error||r.status);x.code=d.error||'';throw x}return d})})}
function guardedSubmit(gate,task){if(!gate.enter())return Promise.resolve({skipped:true});return Promise.resolve().then(task).catch(function(err){gate.release();throw err})}
var core={normalizeFinnishPhone:normalizeFinnishPhone,pathForNeed:pathForNeed,bucketForNeed:bucketForNeed,nextAfterNeed:nextAfterNeed,nextAfterContactSaved:nextAfterContactSaved,nextAfterSubmitSuccess:nextAfterSubmitSuccess,shouldWarnOnExit:shouldWarnOnExit,createSubmitGate:createSubmitGate,buildContactPayload:buildContactPayload,buildSubmitPayload:buildSubmitPayload,postJson:postJson,guardedSubmit:guardedSubmit};
if(typeof module!=='undefined'&&module.exports)module.exports=core;if(global)global.AQOONCaawiCore=core;if(typeof document==='undefined')return;
var ROOT='https://qxracwbsyfibcelasxbs.supabase.co/functions/v1/',CONTACT=ROOT+'family-intake-contact',SUBMIT=ROOT+'family-intake-submit',TRACK=ROOT+'family-funnel-track';
var CITIES=['Vantaa','Helsinki','Espoo','Tampere'],NEEDS=[{id:'kids',label:'Carruurta',sub:'Xannaano, dugsi ama ciyaaro',icon:'👶'},{id:'work',label:'Shaqo',sub:'Shaqo, tababar ama ganacsi',icon:'💼'},{id:'school',label:'Waxbarasho',sub:'Finnish, YKI ama waxbarasho',icon:'🎓'}],HELP='Waxaan kaa caawinayaa inaad fahanto fursadaha kuu jira, waxa aad xaq u leedahay, sida loo codsado, iyo dadka ama barnaamijyada saxda ah ee aan kugu xiriirin karo. Caawimaaddaydu waa bilaash 100%.',SUBS={daycare:[['Xannaano ama päiväkoti','Hel meel xannaano ama faham fursadaha jira'],['Esiopetus','Diyaarinta dugsiga ka hor fasalka 1aad'],['Codsi ama diiwaangelin','Caawimaad buuxinta codsiga ama isdiiwaangelinta'],['Wax kale','Faahfaahinta telefoonka ayaan ka hadli karnaa']],hobby:[['Ciyaaro iyo hiwaayado','Hel waxqabad ama hobby ku habboon ilmaha'],['Dugsiga iyo taageerada ilmaha','Su’aalo ku saabsan dugsiga, luqadda ama taageerada'],['Codsi ama diiwaangelin','Caawimaad codsi ama isdiiwaangelin'],['Wax kale','Faahfaahinta telefoonka ayaan ka hadli karnaa']],work:[['Shaqo raadis ama codsi shaqo','Hel shaqo ama caawimaad codsiga shaqada'],['Kaararka iyo shahaadooyinka shaqada','Tusaale hygieniapassi ama työturvallisuuskortti'],['Barnaamij shaqo ama tababar','Hel barnaamij ama tababar kaa caawin kara shaqo'],['Ganacsi aan bilaabo','Faham sida loo bilaabo ganacsi iyo halka laga helo caawimaad'],['Wax kale','Faahfaahinta telefoonka ayaan ka hadli karnaa']],school:[['Baro Finnish ama hel koorso','Hel koorso ama waddo aad Finnish-ka ku barato'],['Caddee heerkaaga Finnish-ka','YKI wuxuu caddeeyaa heerka luqaddaada Finnish-ka'],['Dhammaystir dugsi ama hel shahaadadaada ugu horreysa','Haddii aadan weli haysan shahaado ama waxbarasho dhammaystiran'],['Waxbarasho ama barnaamij kale','Hel fursad waxbarasho ama barnaamij kugu habboon'],['Wax kale','Faahfaahinta telefoonka ayaan ka hadli karnaa']]};
function uuid(){return crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)})}
function get(k,st){try{return st.getItem(k)||''}catch(e){return''}}
function set(k,v,st){try{st.setItem(k,v)}catch(e){}}
var visitor=get('aqoon_visitor_id',localStorage)||uuid();set('aqoon_visitor_id',visitor,localStorage);var session=get('aqoon_funnel_session',sessionStorage)||uuid();set('aqoon_funnel_session',session,sessionStorage);var requestId=get('aqoon_intake_request',sessionStorage)||uuid();set('aqoon_intake_request',requestId,sessionStorage);var ids={visitor:visitor,session:session,requestId:requestId};
var qs=new URLSearchParams(location.search),refHost='',source=qs.get('utm_source')||'';try{if(document.referrer){var ru=new URL(document.referrer);refHost=ru.hostname;if(!source&&ru.hostname===location.hostname&&ru.pathname.indexOf('/so')===0)source='aqoon-seo'}}catch(e){}if(!source&&qs.get('ttclid'))source='tiktok';if(!source&&qs.get('gclid'))source='google';if(!source&&(qs.get('fbclid')||qs.get('igshid')))source='meta';var attr={referrer_host:refHost||null,utm_source:source||null,utm_medium:qs.get('utm_medium'),utm_campaign:qs.get('utm_campaign')};
var s={screen:'hero',name:'',phone:'',city:'',customCity:'',mainNeed:'',age:'',subNeed:''},screens=[].slice.call(document.querySelectorAll('[data-screen]'));var cityOptions=document.getElementById('cityOptions'),needOptions=document.getElementById('needOptions'),subOptions=document.getElementById('subOptions'),customCityWrap=document.getElementById('customCityWrap'),customCity=document.getElementById('customCity'),customCityContinue=document.getElementById('customCityContinue'),phone=document.getElementById('phone'),name=document.getElementById('name'),contactForm=document.getElementById('contactForm'),contactBtn=document.getElementById('contactBtn'),contactError=document.getElementById('contactError'),finishError=document.getElementById('finishError'),retryBtn=document.getElementById('retryBtn'),leaveModal=document.getElementById('leaveModal'),stayBtn=document.getElementById('stayBtn'),leaveBtn=document.getElementById('leaveBtn'),submitGate=core.createSubmitGate();
function path(){return core.pathForNeed(s.mainNeed)}function bucket(){return core.bucketForNeed(s.mainNeed,s.age)}function finalCity(){return s.city==='Meel kale'?s.customCity.trim():s.city}function needLabel(){var n=NEEDS.find(function(x){return x.id===s.mainNeed});return n?n.label:''}
function track(n,extra){fetch(TRACK,{method:'POST',keepalive:true,headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({event_id:uuid(),visitor_id:visitor,session_id:session,event_name:n,path:'/caawi',screen:s.screen,city:finalCity()||null,main_need:needLabel()||null,sub_need:s.subNeed||null,age_group:s.age||null},attr,extra||{}))}).catch(function(){})}
function progress(){document.querySelectorAll('[data-progress]').forEach(function(el){var p=path(),i=p.indexOf(s.screen);el.innerHTML=p.map(function(_,j){return'<i class="dot '+(j<i?'done ':j===i?'current ':'')+'"></i>'}).join('')})}
function show(x){s.screen=x;if(x==='confirm')exitGuard=false;screens.forEach(function(el){el.classList.toggle('active',el.dataset.screen===x)});progress();window.scrollTo(0,0);if(x==='contact'){track('contact_view');setTimeout(function(){phone.focus({preventScroll:true})},80)}if(x==='explain'){document.getElementById('explainerText').textContent=HELP;document.getElementById('explainIcon').textContent=s.mainNeed==='work'?'💼':s.mainNeed==='school'?'🎓':s.age==='under7'?'👶':'🧒'}if(x==='sub')renderSubs()}
function opt(label,sub,icon,attrs){return'<button class="option" type="button" '+attrs+'>'+(icon?'<span class="icon">'+icon+'</span>':'')+'<span><strong>'+label+'</strong>'+(sub?'<small>'+sub+'</small>':'')+'</span></button>'}
function renderCities(){cityOptions.innerHTML=CITIES.map(function(c){return opt(c,'','📍','data-city="'+c+'"')}).join('')+opt('Meel kale','','📍','data-city="Meel kale"')}
function renderNeeds(){needOptions.innerHTML=NEEDS.map(function(n){return opt(n.label,n.sub,n.icon,'data-need="'+n.id+'"')}).join('')}
function renderSubs(){subOptions.innerHTML=(SUBS[bucket()]||[]).map(function(x,i){return opt(x[0],x[1],'','data-sub-index="'+i+'"')}).join('')}
function err(el,m){el.textContent=m;el.classList.toggle('show',!!m)}
var exitGuard=false,pendingLeave=null,pendingStay=null;function armExitGuard(){if(exitGuard)return;exitGuard=true;try{history.pushState({aqoonForm:true},'',location.href)}catch(e){}}function askBeforeLeaving(onLeave,onStay){pendingLeave=onLeave||null;pendingStay=onStay||null;leaveModal.hidden=false;setTimeout(function(){stayBtn.focus()},20)}function closeLeave(){leaveModal.hidden=true;pendingLeave=null;pendingStay=null}
stayBtn.onclick=function(){var a=pendingStay;closeLeave();if(a)a()};leaveBtn.onclick=function(){var a=pendingLeave;closeLeave();exitGuard=false;if(a)a()};leaveModal.addEventListener('click',function(e){if(e.target===leaveModal){var a=pendingStay;closeLeave();if(a)a()}});window.addEventListener('popstate',function(){if(!core.shouldWarnOnExit(exitGuard,s.screen))return;askBeforeLeaving(function(){history.back()},function(){try{history.pushState({aqoonForm:true},'',location.href)}catch(e){}})});window.addEventListener('beforeunload',function(e){if(core.shouldWarnOnExit(exitGuard,s.screen)){e.preventDefault();e.returnValue=''}});
var contactStarted=false;function started(){if(!contactStarted){contactStarted=true;track('contact_started')}}phone.addEventListener('input',function(){started();if(contactError.classList.contains('show'))err(contactError,'')});name.addEventListener('input',function(){started();if(contactError.classList.contains('show'))err(contactError,'')});phone.addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();name.focus()}});
contactForm.onsubmit=function(e){e.preventDefault();if(contactBtn.disabled)return;var normalized=core.normalizeFinnishPhone(phone.value);s.name=name.value.trim();track('submit_attempt');if(!normalized){track('validation_error');err(contactError,'Lambarka telefoonka sax ma aha. Fadlan hubi oo mar kale isku day. Tusaale: 040 123 4567 ama +358 40 123 4567.');phone.focus();return}s.phone=normalized;if(!s.name){track('validation_error');err(contactError,'Fadlan qor magacaaga.');name.focus();return}err(contactError,'');contactBtn.disabled=true;contactBtn.textContent='Waa la kaydinayaa…';core.postJson(fetch,CONTACT,core.buildContactPayload(s,ids,attr,document.getElementById('website').value)).then(function(d){if(d.phone)s.phone=d.phone;contactBtn.disabled=false;contactBtn.textContent='Sii wad →';show(core.nextAfterContactSaved())}).catch(function(ex){track('submit_error');if(ex.code==='missing_or_invalid_fields'){err(contactError,'Lambarka telefoonka sax ma aha. Fadlan hubi oo mar kale isku day.');phone.focus()}else err(contactError,'Lambarka lama kaydin. Hubi internet-ka oo mar kale isku day.');contactBtn.disabled=false;contactBtn.textContent='Mar kale isku day →'})};
cityOptions.onclick=function(e){var b=e.target.closest('[data-city]');if(!b)return;s.city=b.dataset.city;if(s.city==='Meel kale'){customCityWrap.hidden=false;customCity.focus();return}s.customCity='';customCityWrap.hidden=true;track('city_selected',{city:s.city});show('need')};customCity.oninput=function(){s.customCity=customCity.value;customCityContinue.disabled=!s.customCity.trim()};customCityContinue.onclick=function(){if(s.customCity.trim()){track('city_selected',{city:s.customCity.trim()});show('need')}};
needOptions.onclick=function(e){var b=e.target.closest('[data-need]');if(!b)return;s.mainNeed=b.dataset.need;s.age='';s.subNeed='';track('need_selected');show(core.nextAfterNeed(s.mainNeed))};document.querySelectorAll('[data-age]').forEach(function(b){b.onclick=function(){s.age=b.dataset.age;track('age_selected');show('explain')}});
function finalize(){track('submit_attempt');retryBtn.hidden=true;err(finishError,'');Array.from(subOptions.querySelectorAll('button')).forEach(function(b){b.disabled=true});core.guardedSubmit(submitGate,function(){return core.postJson(fetch,SUBMIT,core.buildSubmitPayload(s,ids,attr,finalCity(),needLabel()))}).then(function(result){if(result&&result.skipped)return;document.getElementById('thanksTitle').textContent='Mahadsanid, '+s.name+'!';document.getElementById('summary').innerHTML='<div class="summary-row"><span>Magaalo</span><strong>'+finalCity()+'</strong></div><div class="summary-row"><span>Waxaad u baahan tahay</span><strong>'+needLabel()+'</strong></div><div class="summary-row"><span>Faahfaahin</span><strong>'+s.subNeed+'</strong></div>';show(core.nextAfterSubmitSuccess())}).catch(function(){track('submit_error');err(finishError,'Faahfaahinta lama dirin, laakiin lambarkaaga waan haynaa. Mar kale isku day.');retryBtn.hidden=false;Array.from(subOptions.querySelectorAll('button')).forEach(function(b){b.disabled=false})})}
subOptions.onclick=function(e){var b=e.target.closest('[data-sub-index]');if(!b)return;var x=(SUBS[bucket()]||[])[+b.dataset.subIndex];s.subNeed=x?x[0]:'';track('sub_selected');finalize()};retryBtn.onclick=finalize;document.querySelectorAll('[data-go]').forEach(function(b){b.onclick=function(){if(s.screen==='hero'){track('start');armExitGuard()}show(b.dataset.go)}});document.querySelectorAll('[data-back]').forEach(function(b){b.onclick=function(){var p=path(),i=p.indexOf(s.screen);if(i<=0){askBeforeLeaving(function(){show('hero')});return}show(p[i-1])}});document.getElementById('resetBtn').onclick=function(){exitGuard=false;sessionStorage.removeItem('aqoon_intake_request');location.href='/caawi'};
renderCities();renderNeeds();progress();track('page_view');
})(typeof window!=='undefined'?window:(typeof globalThis!=='undefined'?globalThis:null));