(function(g){'use strict';
var FORM_VERSION='phone-first-v2-multineed';
function phone(v){var r=String(v||'').trim().replace(/[\s().-]/g,'');if(!r||r.indexOf('+')>0||((r.match(/\+/g)||[]).length>1))return'';if(r.indexOf('00358')===0)r='+358'+r.slice(5);else if(r.indexOf('358')===0)r='+358'+r.slice(3);if(r.indexOf('+358')===0){if(!/^\+358\d+$/.test(r))return'';var n=r.slice(4);if(n[0]==='0')n=n.slice(1);return/^[1-9]\d{6,9}$/.test(n)?'+358'+n:''}return/^0\d{7,10}$/.test(r)?'+358'+r.slice(1):''}
function pathForNeed(n,more){var b=more?['need']:['contact','city','need'];return n==='kids'?b.concat(['age','sub','more']):n==='other'?b.concat(['more']):b.concat(['sub','more'])}
function bucketForNeed(n,a){return n==='kids'?(a==='under7'?'daycare':'school_child'):n}
function normalizeRequests(rs){var out=[],seen={};(rs||[]).forEach(function(r){var m=String(r&&r.main_need||'').trim(),s=String(r&&r.sub_need||'').trim(),a=String(r&&r.age_group||'').trim()||null;if(m&&s&&!seen[m]){seen[m]=1;out.push({main_need:m,sub_need:s,age_group:a})}});return out.slice(0,4)}
function buildContactPayload(s,i,a,w){return Object.assign({request_id:i.requestId,visitor_id:i.visitor,session_id:i.session,name:s.name,phone:s.phone,form_version:FORM_VERSION,website:w||''},a||{})}
function buildSubmitPayload(s,i,a,c,rs,d){var l=normalizeRequests(rs),f=l[0]||{main_need:'',sub_need:'',age_group:null},x=d||s.diagnostics||{};return Object.assign({request_id:i.requestId,visitor_id:i.visitor,session_id:i.session,lang:'so',form_version:FORM_VERSION,name:s.name,phone:s.phone,city:c,main_need:f.main_need,sub_need:f.sub_need,age_group:f.age_group,additional_needs:l.slice(1),work_diagnostic:x.work||null,school_diagnostic:x.school||null,programs_diagnostic:x.other||null,website:''},a||{})}
function postJson(f,u,p){return f(u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}).then(function(r){return r.json().catch(function(){return{}}).then(function(d){if(!r.ok){var e=Error(d.error||r.status);e.code=d.error||'';throw e}return d})})}
function gate(){var l=false;return{enter:function(){if(l)return false;l=true;return true},release:function(){l=false}}}function guardedSubmit(x,t){if(!x.enter())return Promise.resolve({skipped:true});return Promise.resolve().then(t).catch(function(e){x.release();throw e})}
var core={FORM_VERSION:FORM_VERSION,normalizeFinnishPhone:phone,pathForNeed:pathForNeed,bucketForNeed:bucketForNeed,nextAfterNeed:function(n){return n==='kids'?'age':n==='other'?'more':'sub'},nextAfterContactSaved:function(){return'city'},nextAfterSubSelected:function(){return'more'},nextAfterSubmitSuccess:function(){return'confirm'},shouldWarnOnExit:function(x,s){return!!x&&s!=='hero'&&s!=='confirm'},createSubmitGate:gate,normalizeRequests:normalizeRequests,buildContactPayload:buildContactPayload,buildSubmitPayload:buildSubmitPayload,postJson:postJson,guardedSubmit:guardedSubmit};
if(typeof module!=='undefined'&&module.exports)module.exports=core;if(g)g.AQOONCaawiCore=core;if(typeof document==='undefined')return;
var ROOT='https://qxracwbsyfibcelasxbs.supabase.co/functions/v1/',CONTACT=ROOT+'family-intake-contact',SUBMIT=ROOT+'family-intake-submit',TRACK=ROOT+'family-funnel-track';
var NEEDS=[['kids','Carruur iyo skuul','Xannaano, skuulka ilmaha, taageero ama harrastus','👶'],['work','Shaqo','Shaqo raadis, CV, tababar ama ganacsi','💼'],['school','Waxbarasho','Finnish, YKI, shahaado ama waxbarasho kale','🎓'],['other','Arrin kale','Wax aan kor ku qornayn ama haddii aadan hubin meesha laga bilaabo','🧭']],CITIES=['Vantaa','Helsinki','Espoo','Tampere'];
var SUBS={daycare:[['Päiväkoti ama xannaano','Hel xannaano ama faham codsiga'],['Esiopetus','Waxbarashada ilmaha ka hor fasalka 1aad'],['Codsi ama diiwaangelin','Caawimaad buuxinta codsiga'],['Ciyaar ama harrastus','Hel hawl ku habboon ilmaha']],school_child:[['Skuulka iyo taageerada ilmaha','Su’aalo ku saabsan skuulka, luqadda ama taageerada'],['Harrastus ama ciyaar','Hel ciyaar ama harrastus ku habboon ilmaha'],['Wilma ama fariin skuul','Faham fariinta ama tallaabada xigta'],['Codsi ama diiwaangelin','Caawimaad ku saabsan codsi']],work:[['Shaqo raadis','Hel shaqo ama faham halka laga bilaabo'],['CV ama codsi shaqo','Diyaari CV ama työhakemus'],['Tababar ama xirfad','Koorso ama waddo lagu horumariyo xirfadda'],['Bilaabidda ganacsi','Qorshaha ganacsiga iyo tallaabada koowaad']],school:[['Barashada Finnish-ka','Koorso Finnish ah'],['YKI','Imtixaanka YKI ama diyaarintiisa'],['Waxbarasho ama shahaado','Ammattikoulu, waxbarasho sare ama shahaado'],['Wax kale oo waxbarasho ah','Waddo aan kor ku qornayn']]};
function id(){return crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)})}function get(k,s){try{return s.getItem(k)||''}catch(e){return''}}function set(k,v,s){try{s.setItem(k,v)}catch(e){}}function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
var consent=get('aqoon_analytics_consent',localStorage),visitor=consent==='yes'?(get('aqoon_visitor_id',localStorage)||id()):id();if(consent==='yes')set('aqoon_visitor_id',visitor,localStorage);var ids={visitor:visitor,session:id(),requestId:get('aqoon_intake_request',sessionStorage)||id()};set('aqoon_intake_request',ids.requestId,sessionStorage);var q=new URLSearchParams(location.search),source=q.get('utm_source')||'',ref='';try{if(document.referrer){var u=new URL(document.referrer);ref=u.hostname;if(!source&&u.hostname===location.hostname&&u.pathname.indexOf('/so')===0)source='aqoon-seo'}}catch(e){}var attr={referrer_host:ref||null,utm_source:source||null,utm_medium:q.get('utm_medium'),utm_campaign:q.get('utm_campaign')};
var s={screen:'hero',name:'',phone:'',city:'',customCity:'',mainNeed:'',age:'',subNeed:'',requests:[],diagnostics:{},addingMore:false},screens=[].slice.call(document.querySelectorAll('[data-screen]')),E=function(x){return document.getElementById(x)},submitGate=gate(),exitGuard=false,contactStarted=false,pendingLeave=null,pendingStay=null;
function label(){var n=NEEDS.filter(function(x){return x[0]===s.mainNeed})[0];return n?n[1]:''}function city(){return s.city==='Meel kale'?s.customCity.trim():s.city}function p(){return pathForNeed(s.mainNeed,s.addingMore)}function track(n,x){if(consent!=='yes')return;fetch(TRACK,{method:'POST',keepalive:true,headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({event_id:id(),visitor_id:ids.visitor,session_id:ids.session,event_name:n,form_version:FORM_VERSION,path:'/caawi',screen:s.screen,city:city()||null,main_need:label()||null,sub_need:s.subNeed||null,age_group:s.age||null},attr,x||{}))}).catch(function(){})}
function option(a,b,c,d){return'<button class="option" type="button" '+d+'>'+(c?'<span class="icon">'+c+'</span>':'')+'<span><strong>'+esc(a)+'</strong>'+(b?'<small>'+esc(b)+'</small>':'')+'</span></button>'}function progress(){document.querySelectorAll('[data-progress]').forEach(function(e){var z=p(),i=z.indexOf(s.screen);e.innerHTML=z.map(function(_,j){return'<i class="dot '+(j<i?'done ':j===i?'current ':'')+'"></i>'}).join('')})}
function renderNeeds(){var used={};s.requests.forEach(function(r){used[r.main_need]=1});var ns=NEEDS.filter(function(n){return!s.addingMore||!used[n[1]]});E('needOptions').innerHTML=ns.map(function(n){return option(n[1],n[2],n[3],'data-need="'+n[0]+'"')}).join('')}function renderSubs(){E('subOptions').innerHTML=(SUBS[bucketForNeed(s.mainNeed,s.age)]||[]).map(function(x,i){return option(x[0],x[1],'','data-sub-index="'+i+'"')}).join('')}function add(){var r={main_need:label(),sub_need:s.subNeed,age_group:s.mainNeed==='kids'?s.age||null:null},i=s.requests.findIndex(function(x){return x.main_need===r.main_need});if(!r.main_need||!r.sub_need)return;if(i<0)s.requests.push(r);else s.requests[i]=r;s.requests=normalizeRequests(s.requests)}function renderMore(){E('moreList').innerHTML=s.requests.map(function(r,i){return'<div class="summary-row"><span>'+(i?'Caawimaad kale':'Caawimaadda ugu weyn')+'</span><strong>'+esc(r.main_need)+' · '+esc(r.sub_need)+'</strong></div>'}).join('');E('addMoreBtn').hidden=s.requests.length>=NEEDS.length;E('sendRequestBtn').textContent=s.requests.length>1?'Dir codsiga ('+s.requests.length+' arrimood) →':'Dir codsiga →'}
function show(x){s.screen=x;if(x==='confirm')exitGuard=false;screens.forEach(function(e){e.classList.toggle('active',e.dataset.screen===x)});if(x==='need')renderNeeds();if(x==='sub')renderSubs();if(x==='more'){renderMore();track('more_help_view')}progress();scrollTo(0,0);if(x==='contact'){track('contact_view');setTimeout(function(){E('phone').focus()},80)}}
E('cityOptions').innerHTML=CITIES.map(function(c){return option(c,'','📍','data-city="'+c+'"')}).join('')+option('Meel kale','','📍','data-city="Meel kale"');
E('contactConsent').onchange=function(){E('sendRequestBtn').disabled=!E('contactConsent').checked};
E('analyticsChoice').hidden=!!consent;E('analyticsAccept').onclick=function(){consent='yes';set('aqoon_analytics_consent','yes',localStorage);E('analyticsChoice').hidden=true;track('analytics_consent')};E('analyticsDecline').onclick=function(){consent='no';set('aqoon_analytics_consent','no',localStorage);E('analyticsChoice').hidden=true};
E('phone').oninput=E('name').oninput=function(){if(!contactStarted){contactStarted=true;track('contact_started')}E('contactError').classList.remove('show')};E('contactForm').onsubmit=function(e){e.preventDefault();var n=phone(E('phone').value);s.name=E('name').value.trim();track('submit_attempt');if(!n||!s.name){track('validation_error');E('contactError').textContent=!n?'Lambarka telefoonka sax ma aha.':'Fadlan qor magacaaga.';E('contactError').classList.add('show');return}s.phone=n;E('contactError').classList.remove('show');E('contactBtn').disabled=true;postJson(fetch,CONTACT,buildContactPayload(s,ids,attr,E('website').value)).then(function(){E('contactBtn').disabled=false;show('city')}).catch(function(){track('submit_error');E('contactError').textContent='Lambarka lama kaydin. Hubi internet-ka oo mar kale isku day.';E('contactError').classList.add('show');E('contactBtn').disabled=false})};
E('cityOptions').onclick=function(e){var b=e.target.closest('[data-city]');if(!b)return;s.city=b.dataset.city;if(s.city==='Meel kale'){E('customCityWrap').hidden=false;E('customCity').focus();return}E('customCityWrap').hidden=true;track('city_selected');show('need')};E('customCity').oninput=function(){s.customCity=E('customCity').value;E('customCityContinue').disabled=!s.customCity.trim()};E('customCityContinue').onclick=function(){if(s.customCity.trim())show('need')};
E('needOptions').onclick=function(e){var b=e.target.closest('[data-need]');if(!b)return;s.mainNeed=b.dataset.need;s.age='';s.subNeed='';track('need_selected');if(s.mainNeed==='other'){s.subNeed='Wax aan kor ku qornayn';add();s.addingMore=false;show('more');return}show(core.nextAfterNeed(s.mainNeed))};document.querySelectorAll('[data-age]').forEach(function(b){b.onclick=function(){s.age=b.dataset.age;track('age_selected');show('sub')}});E('subOptions').onclick=function(e){var b=e.target.closest('[data-sub-index]');if(!b)return;s.subNeed=(SUBS[bucketForNeed(s.mainNeed,s.age)]||[])[+b.dataset.subIndex][0];track('sub_selected');add();s.addingMore=false;show('more')};
E('addMoreBtn').onclick=function(){s.addingMore=true;s.mainNeed='';s.age='';s.subNeed='';show('need')};function finish(){if(!s.requests.length||!E('contactConsent').checked)return;track('send_request');E('retryBtn').hidden=true;E('finishError').classList.remove('show');E('sendRequestBtn').disabled=true;E('addMoreBtn').disabled=true;guardedSubmit(submitGate,function(){return postJson(fetch,SUBMIT,buildSubmitPayload(s,ids,attr,city(),s.requests,s.diagnostics))}).then(function(){E('thanksTitle').textContent='Mahadsanid, '+s.name+'!';E('summary').innerHTML='<div class="summary-row"><span>Magaalo</span><strong>'+esc(city())+'</strong></div>'+E('moreList').innerHTML;show('confirm')}).catch(function(){track('submit_error');E('finishError').textContent='Faahfaahinta lama dirin, laakiin lambarkaaga waan haynaa. Mar kale isku day.';E('finishError').classList.add('show');E('retryBtn').hidden=false;E('sendRequestBtn').disabled=false;E('addMoreBtn').disabled=false})}E('sendRequestBtn').onclick=finish;E('retryBtn').onclick=finish;function closeLeave(){E('leaveModal').hidden=true;pendingLeave=null;pendingStay=null}function askBeforeLeaving(leave,stay){pendingLeave=leave;pendingStay=stay;E('leaveModal').hidden=false;E('stayBtn').focus()}E('stayBtn').onclick=function(){var a=pendingStay;closeLeave();if(a)a()};E('leaveBtn').onclick=function(){var a=pendingLeave;closeLeave();exitGuard=false;if(a)a()};window.addEventListener('beforeunload',function(e){if(core.shouldWarnOnExit(exitGuard,s.screen)){e.preventDefault();e.returnValue=''}});document.querySelectorAll('[data-go]').forEach(function(b){b.onclick=function(){if(s.screen==='hero')exitGuard=true;show(b.dataset.go)}});document.querySelectorAll('[data-back]').forEach(function(b){b.onclick=function(){if(s.addingMore&&s.screen==='need'){s.addingMore=false;show('more');return}var z=p(),i=z.indexOf(s.screen);if(i>0){show(z[i-1]);return}askBeforeLeaving(function(){show('hero')})}});E('resetBtn').onclick=function(){sessionStorage.removeItem('aqoon_intake_request');location.href='/caawi'};show('hero');track('page_view');
})(typeof window!=='undefined'?window:globalThis);
