import { createClient } from "npm:@supabase/supabase-js@2";
const ORIGIN="https://aqoon.live";
const FORM_VERSION="phone-first-v2-multineed";
function cors(){return {"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};}
function clean(v:unknown,max:number){return typeof v==="string"?v.trim().slice(0,max):"";}async function clientKey(req:Request){const raw=(req.headers.get("x-forwarded-for")||req.headers.get("cf-connecting-ip")||"").split(",")[0].trim();if(!raw)return null;const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(raw));return Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,"0")).join("");}function isUuid(v:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);}
function normalizeFinnishPhone(v:unknown){let raw=clean(v,40).replace(/[\s().-]/g,"");if(!raw)return "";if(raw.startsWith("00358"))raw="+358"+raw.slice(5);else if(raw.startsWith("358"))raw="+358"+raw.slice(3);if(raw.startsWith("+358")){if(!/^\+358\d+$/.test(raw))return "";let n=raw.slice(4);if(n.startsWith("0"))n=n.slice(1);if(!/^[1-9]\d{6,9}$/.test(n))return "";return "+358"+n;}if(!/^\d+$/.test(raw))return "";if(/^0\d{7,10}$/.test(raw))return "+358"+raw.slice(1);return "";}
function cleanAdditional(v:unknown){if(!Array.isArray(v))return [];const out:any[]=[];const seen=new Set<string>();for(const item of v.slice(0,6)){if(!item||typeof item!=="object")continue;const main=clean((item as any).main_need,100),sub=clean((item as any).sub_need,300),age=clean((item as any).age_group,50)||null;if(!main||!sub||seen.has(main))continue;seen.add(main);out.push({main_need:main,sub_need:sub,age_group:age});if(out.length>=3)break;}return out;}
Deno.serve(async(req)=>{const h=cors();if(req.method==="OPTIONS")return new Response(null,{status:204,headers:h});if(req.method!=="POST")return new Response(JSON.stringify({error:"method_not_allowed"}),{status:405,headers:h});let b:any={};try{b=await req.json()}catch{return new Response(JSON.stringify({error:"invalid_json"}),{status:400,headers:h})}
 if(clean(b.website,50))return new Response(JSON.stringify({ok:true}),{status:200,headers:h});const name=clean(b.name,120),phone=normalizeFinnishPhone(b.phone),city=clean(b.city,100),main=clean(b.main_need,100),sub=clean(b.sub_need,300),age=clean(b.age_group,50)||null,lang=clean(b.lang,10)||"so",workDiag=clean(b.work_diagnostic,50)||null,schoolDiag=clean(b.school_diagnostic,50)||null,programsDiag=clean(b.programs_diagnostic,50)||null,additional=cleanAdditional(b.additional_needs),contactConsent=b.contact_consent===true;const sid=clean(b.session_id,50),vid=clean(b.visitor_id,50),rid=clean(b.request_id,50);
 if(!name||!phone||!city||!main||!sub||!contactConsent||!isUuid(sid)||!isUuid(vid)||!isUuid(rid))return new Response(JSON.stringify({error:"missing_or_invalid_fields"}),{status:400,headers:h});const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return new Response(JSON.stringify({error:"server_config"}),{status:500,headers:h});const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const rateKey=await clientKey(req);if(rateKey){const {data}=await db.rpc("take_family_intake_rate_limit",{p_client_key:rateKey,p_endpoint:"submit",p_limit:8});const guard=Array.isArray(data)?data[0]:null;if(guard&&!guard.allowed)return new Response(JSON.stringify({error:"too_many_requests",retry_after_seconds:guard.retry_after_seconds}),{status:429,headers:{...h,"Retry-After":String(guard.retry_after_seconds||3600)}});}const contact=await db.from("family_intake_contacts").select("id,phone").eq("request_id",rid).maybeSingle();if(contact.error)return new Response(JSON.stringify({error:"db_error"}),{status:500,headers:h});if(!contact.data||contact.data.phone!==phone)return new Response(JSON.stringify({error:"contact_start_required"}),{status:409,headers:h});const consentAt=new Date().toISOString(),tier=main==="Carruur iyo skuul"?1:2;
 const existing=await db.from("family_leads").select("id").eq("intake_request_id",rid).maybeSingle();if(existing.error)return new Response(JSON.stringify({error:"db_error"}),{status:500,headers:h});if(existing.data){const leadUpdate=await db.from("family_leads").update({name,phone,city,main_need:main,sub_need:sub,age_group:age,additional_needs:additional,form_version:FORM_VERSION,work_diagnostic:workDiag,school_diagnostic:schoolDiag,programs_diagnostic:programsDiag,contact_consent_at:consentAt,updated_at:consentAt}).eq("id",existing.data.id);if(leadUpdate.error)return new Response(JSON.stringify({error:"lead_update_failed"}),{status:500,headers:h});const contactUpdate=await db.from("family_intake_contacts").update({completed:true,phone,city,main_need:main,sub_need:sub,age_group:age,additional_needs:additional,form_version:FORM_VERSION,work_diagnostic:workDiag,school_diagnostic:schoolDiag,programs_diagnostic:programsDiag,contact_consent_at:consentAt,updated_at:consentAt}).eq("request_id",rid);if(contactUpdate.error)return new Response(JSON.stringify({error:"contact_update_failed"}),{status:500,headers:h});return new Response(JSON.stringify({ok:true,id:existing.data.id,duplicate:true,phone}),{status:200,headers:h});}
 const lead=await db.from("family_leads").insert({name,phone,city,main_need:main,sub_need:sub,age_group:age,additional_needs:additional,tier,status:"new",source:"caawi",lang,form_version:FORM_VERSION,analytics_session_id:sid,analytics_visitor_id:vid,intake_request_id:rid,referrer_host:clean(b.referrer_host,200)||null,utm_source:clean(b.utm_source,100)||null,utm_medium:clean(b.utm_medium,100)||null,utm_campaign:clean(b.utm_campaign,150)||null,work_diagnostic:workDiag,school_diagnostic:schoolDiag,programs_diagnostic:programsDiag,contact_consent_at:consentAt}).select("id").single();if(lead.error)return new Response(JSON.stringify({error:"db_error"}),{status:500,headers:h});
 const contactUpdate=await db.from("family_intake_contacts").update({completed:true,phone,city,main_need:main,sub_need:sub,age_group:age,additional_needs:additional,form_version:FORM_VERSION,work_diagnostic:workDiag,school_diagnostic:schoolDiag,programs_diagnostic:programsDiag,contact_consent_at:consentAt,updated_at:consentAt}).eq("request_id",rid);if(contactUpdate.error)return new Response(JSON.stringify({error:"contact_update_failed"}),{status:500,headers:h});
 const funnel=await db.from("family_funnel_events").insert({event_id:crypto.randomUUID(),visitor_id:vid,session_id:sid,event_name:"submit_success",form_version:FORM_VERSION,path:"/caawi",screen:"more",city,main_need:main,sub_need:sub,age_group:age,work_diagnostic:workDiag,school_diagnostic:schoolDiag,programs_diagnostic:programsDiag,referrer_host:clean(b.referrer_host,200)||null,utm_source:clean(b.utm_source,100)||null,utm_medium:clean(b.utm_medium,100)||null,utm_campaign:clean(b.utm_campaign,150)||null,device_type:/mobi|iphone|android/i.test(req.headers.get("user-agent")||"")?"mobile":"desktop"});if(funnel.error&&funnel.error.code!=="23505")return new Response(JSON.stringify({error:"funnel_event_write_failed"}),{status:500,headers:h});
 return new Response(JSON.stringify({ok:true,id:lead.data.id,phone,additional_needs:additional,form_version:FORM_VERSION}),{status:200,headers:h});});
