(()=>{'use strict';
const END='https://qxracwbsyfibcelasxbs.supabase.co/functions/v1/family-leads-manage';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let activeDelete=null;
async function api(body){const r=await fetch(END,{method:'POST',headers:window.AqoonAuthHeaders(),body:JSON.stringify(body),cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.detail||d.error||'Request failed');return d}
function refresh(){const b=document.getElementById('refresh');if(b)b.click();else location.reload()}
function toast(msg,bad=false){let t=document.getElementById('crmManageToast');if(!t){t=document.createElement('div');t.id='crmManageToast';t.className='crm-manage-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.toggle('bad',bad);t.classList.add('show');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.remove('show'),2600)}
function ensureAddButton(){const header=document.querySelector('#crm .crm-header');if(!header||document.getElementById('crmAddLead'))return;const b=document.createElement('button');b.type='button';b.id='crmAddLead';b.className='crm-add-btn';b.setAttribute('aria-label','Add family or lead');b.innerHTML='<span>＋</span><b>Add family / lead</b>';header.appendChild(b);b.onclick=openAdd}
function ensureDialog(){if(document.getElementById('crmManageDialog'))return;const wrap=document.createElement('div');wrap.id='crmManageDialog';wrap.className='crm-manage-modal hidden';wrap.innerHTML='<div class="crm-manage-sheet" role="dialog" aria-modal="true" aria-labelledby="crmManageTitle"><div class="crm-manage-head"><div><span class="eyebrow">MANUAL CRM ENTRY</span><h2 id="crmManageTitle">Add family / lead</h2></div><button type="button" class="crm-manage-x" data-close>×</button></div><p class="crm-manage-intro">Name and phone are enough to save the contact now. Fill the rest only if you already know it.</p><form id="crmAddForm"><div class="crm-manage-grid"><label>Name *<input name="name" required autocomplete="name" placeholder="Family / contact name"></label><label>Phone *<input name="phone" required inputmode="tel" autocomplete="tel" placeholder="+358…"></label><label>City<input name="city" autocomplete="address-level2" placeholder="Helsinki, Vantaa…"></label><label>Main need<input name="main_need" list="crmNeedOptions" placeholder="Work, school, daycare…"></label><label class="wide">More specific need<input name="sub_need" placeholder="What do they need help with?"></label><label>Source<select name="manual_source"><option value="manual">Manual</option><option value="phone">Phone call</option><option value="tiktok-dm">TikTok DM</option><option value="whatsapp">WhatsApp</option><option value="in-person">In person</option><option value="referral">Referral</option><option value="other">Other</option></select></label><label>Age / life stage<input name="age_group" placeholder="Optional"></label><label class="wide">Notes<textarea name="notes" rows="3" placeholder="Anything useful before the first interview"></textarea></label></div><datalist id="crmNeedOptions"><option value="Carruur iyo skuul"><option value="Shaqo"><option value="Waxbarasho"><option value="Arrin kale"><option value="Päiväkoti / varhaiskasvatus"><option value="Skuulka iyo taageerada ilmaha"><option value="Ciyaaro iyo harrastukset"></datalist><button class="btn teal crm-save" type="submit">Save to CRM</button></form></div>';document.body.appendChild(wrap);wrap.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeDialog);wrap.addEventListener('click',e=>{if(e.target===wrap)closeDialog()});wrap.querySelector('#crmAddForm').onsubmit=saveLead}
function openAdd(){ensureDialog();const d=document.getElementById('crmManageDialog');d.classList.remove('hidden');document.body.classList.add('crm-modal-open');setTimeout(()=>d.querySelector('input[name="name"]')?.focus(),80)}
function closeDialog(){document.getElementById('crmManageDialog')?.classList.add('hidden');document.body.classList.remove('crm-modal-open')}
async function saveLead(e){e.preventDefault();const f=e.currentTarget,b=f.querySelector('button[type="submit"]'),fd=new FormData(f);b.disabled=true;b.textContent='Saving…';try{await api({action:'create',name:fd.get('name'),phone:fd.get('phone'),city:fd.get('city'),main_need:fd.get('main_need'),sub_need:fd.get('sub_need'),age_group:fd.get('age_group'),notes:fd.get('notes'),manual_source:fd.get('manual_source')});f.reset();closeDialog();toast('Family added to CRM');setTimeout(refresh,250)}catch(err){toast(err.message||'Could not add family',true)}finally{b.disabled=false;b.textContent='Save to CRM'}}
function confirmDelete(id,name,onDone){activeDelete={id,name,onDone};let d=document.getElementById('crmDeleteDialog');if(!d){d=document.createElement('div');d.id='crmDeleteDialog';d.className='crm-manage-modal hidden';d.innerHTML='<div class="crm-manage-sheet crm-delete-sheet" role="dialog" aria-modal="true"><div class="crm-manage-head"><div><span class="eyebrow">REMOVE CRM FAMILY</span><h2>Delete permanently?</h2></div><button type="button" class="crm-manage-x" data-del-close>×</button></div><p id="crmDeleteText"></p><div class="crm-delete-note">This removes the CRM family and its saved first-interview records. Anonymous funnel analytics remain untouched.</div><div class="crm-delete-actions"><button class="btn secondary" type="button" data-del-close>Cancel</button><button class="btn crm-delete-confirm" id="crmDeleteConfirm" type="button">Delete permanently</button></div></div>';document.body.appendChild(d);d.querySelectorAll('[data-del-close]').forEach(x=>x.onclick=()=>d.classList.add('hidden'));d.querySelector('#crmDeleteConfirm').onclick=deleteLead}d.querySelector('#crmDeleteText').innerHTML='Remove <strong>'+esc(name)+'</strong> from the CRM?';d.classList.remove('hidden')}
async function deleteLead(){if(!activeDelete)return;const b=document.getElementById('crmDeleteConfirm');b.disabled=true;b.textContent='Deleting…';try{await api({action:'delete',id:activeDelete.id});document.getElementById('crmDeleteDialog').classList.add('hidden');toast('Removed from CRM');const onDone=activeDelete.onDone;activeDelete=null;if(onDone)onDone();setTimeout(refresh,250)}catch(err){toast(err.message||'Could not remove family',true)}finally{b.disabled=false;b.textContent='Delete permanently'}}
window.AqoonCrmManage={openAdd,confirmDelete};
const obs=new MutationObserver(()=>{ensureAddButton()});function start(){ensureAddButton();ensureDialog();const crm=document.getElementById('crm');if(crm)obs.observe(crm,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest('[data-tab="crm"],#refresh'))setTimeout(ensureAddButton,250)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
