(()=>{'use strict';
const END='https://qxracwbsyfibcelasxbs.supabase.co/functions/v1/family-leads-admin';
let leadId='';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const api=async body=>{const response=await fetch(END,{method:'POST',headers:window.AqoonAuthHeaders(),body:JSON.stringify(body),cache:'no-store'}),data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.detail||data.error||'Could not save household member');return data};
function lead(){return(window.AqoonApp?.leads||[]).find(row=>row.id===leadId)||null}
function members(){const householdId=lead()?.household_id;return(window.AqoonApp?.householdPeople||[]).filter(row=>row.household_id===householdId)}
function needs(){const householdId=lead()?.household_id;return(window.AqoonApp?.familyNeeds||[]).filter(row=>row.household_id===householdId&&row.status!=='archived')}
function host(){let card=document.getElementById('householdPeopleCard');if(card)return card;const capture=document.querySelector('#drawer .interview-capture');if(!capture)return null;card=document.createElement('section');card.id='householdPeopleCard';card.className='household-people-card';capture.insertAdjacentElement('afterend',card);return card}
function label(row){return[row.display_label,row.role,row.age_years!==null&&row.age_years!==undefined?row.age_years+' years':row.age_band].filter(Boolean).join(' · ')}
function render(){const card=host(),current=lead();if(!card||!current?.household_id){card?.remove();return}const people=members(),open=card.dataset.open==='1',availableNeeds=needs().filter(item=>!item.subject_person_id);card.innerHTML='<div class="household-people-head"><div><strong>Household members</strong><small>'+people.length+' explicit record'+(people.length===1?'':'s')+' · age-band hints are not people</small></div><button type="button" id="householdAddMember">'+(open?'Cancel':'+ Add person')+'</button></div><div class="household-people-list">'+people.map(person=>'<span>'+esc(label(person))+'</span>').join('')+'</div>'+(open?'<form id="householdMemberForm"><div class="household-member-grid"><label>Role<select id="householdMemberRole"><option value="child">Child</option><option value="adult">Adult</option><option value="dependent">Dependent</option><option value="other">Other</option></select></label><label>Private label<input id="householdMemberLabel" maxlength="80" placeholder="Child 1 — no full name needed" required></label><label>Age band<select id="householdMemberAgeBand"><option value="">Not recorded</option><option>Under 3</option><option>Age 3–6</option><option>Grades 1–9</option><option>Older child</option><option>Adult</option></select></label><label>Exact age (optional)<input id="householdMemberAge" type="number" min="0" max="120" inputmode="numeric"></label><label class="household-member-wide">Link an existing need<select id="householdMemberNeed"><option value="">Do not link yet</option>'+availableNeeds.map(item=>'<option value="'+esc(item.id)+'">'+esc([item.need_domain,item.raw_sub_need,item.age_group].filter(Boolean).join(' · '))+'</option>').join('')+'</select></label></div><p>Only create a person when the operator has explicitly identified them. Do not turn a future age-band hint into a child record.</p><button class="btn primary" id="householdMemberSave" type="submit">Save member</button><span id="householdMemberStatus"></span></form>':'');document.getElementById('householdAddMember').onclick=()=>{card.dataset.open=open?'0':'1';render()};document.getElementById('householdMemberForm')?.addEventListener('submit',save)}
async function save(event){event.preventDefault();const button=document.getElementById('householdMemberSave'),status=document.getElementById('householdMemberStatus'),displayLabel=document.getElementById('householdMemberLabel').value.trim();if(!displayLabel){status.textContent='Add a private label.';return}button.disabled=true;status.textContent='Saving…';try{const result=await api({action:'save_household_member',lead_id:leadId,role:document.getElementById('householdMemberRole').value,display_label:displayLabel,age_band:document.getElementById('householdMemberAgeBand').value||null,age_years:document.getElementById('householdMemberAge').value||null,family_need_id:document.getElementById('householdMemberNeed').value||null});window.AqoonApp?.patchHouseholdLocal?.(result.person,result.need);const card=host();card.dataset.open='0';render()}catch(error){status.textContent=error.message}finally{button.disabled=false}}
const style=document.createElement('style');style.textContent='.household-people-card{margin:12px 0;padding:12px;border:1px solid var(--l);border-radius:14px;background:#f8fbfa}.household-people-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.household-people-head strong{display:block;font-size:13px}.household-people-head small{display:block;color:var(--m);font-size:9px;margin-top:2px}.household-people-head button{border:1px solid #cbe7e4;background:#fff;color:var(--td);border-radius:9px;padding:8px 10px;font-size:10px;font-weight:800}.household-people-list{display:flex;flex-wrap:wrap;gap:5px;margin-top:8px}.household-people-list span{background:#fff;border:1px solid var(--l);border-radius:999px;padding:5px 8px;font-size:9px}.household-member-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.household-member-grid label{font-size:9px;font-weight:700}.household-member-grid input,.household-member-grid select{width:100%;margin-top:4px;border:1px solid var(--l);border-radius:8px;padding:8px;font:inherit;box-sizing:border-box}.household-member-wide{grid-column:1/-1}#householdMemberForm p,#householdMemberStatus{font-size:9px;color:var(--m)}';document.head.appendChild(style);
const originalOpen=window.openInterview;window.openInterview=function(id){if(originalOpen)originalOpen.call(this,id);leadId=id||'';setTimeout(render,0)};window.addEventListener('dataUpdated',event=>{if(leadId&&['household','leads'].includes(event.detail?.scope))render()});
})();
