(()=>{'use strict';
const END='https://qxracwbsyfibcelasxbs.supabase.co/functions/v1/family-incomplete-admin';
const $=id=>document.getElementById(id);
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const SUBS={
  'Carruur iyo skuul':['Päiväkoti ama xannaano','Esiopetus','Skuulka iyo taageerada ilmaha','Harrastus ama ciyaar','Codsi ama diiwaangelin'],
  'Shaqo':['Shaqo raadis','CV ama codsi shaqo','Tababar ama xirfad','Bilaabidda ganacsi'],
  'Waxbarasho':['Barashada Finnish-ka','YKI','Waxbarasho ama shahaado','Wax kale oo waxbarasho ah'],
  'Arrin kale':['Wax aan kor ku qornayn']
};
let active=null;
function pw(){return sessionStorage.getItem('aqoon_tracker_password')||''}
function authToken(){return sessionStorage.getItem('aqoon_auth_token')||''}
async function api(body){
  const headers={'Content-Type':'application/json','x-tracker-password':pw()},token=authToken();
  if(token)headers.Authorization='Bearer '+token;
  const r=await fetch(END,{method:'POST',headers,body:JSON.stringify(body),cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||d.error||'Request failed');return d
}
function ensureUI(){if($('incompleteDrawer'))return;const style=document.createElement('style');style.textContent='.intake-select{width:100%;min-height:52px;border:1px solid #e4dfd3;border-radius:16px;background:#fff;padding:10px 12px;font:inherit;color:#123554}.intake-error{color:#a33a32;font-size:13px;margin-top:8px}.intake-hint{font-size:12px;color:#687281;margin:5px 0 0}';document.head.appendChild(style);
const el=document.createElement('section');el.id='incompleteDrawer';el.className='drawer hidden';el.innerHTML='<div class="drawer-card"><div class="drawer-top"><div><h2 id="incName">Finish request</h2><small class="muted" id="incMeta"></small></div><button class="btn secondary" id="incClose" type="button">Close</button></div><div class="question"><label>City</label><input id="incCity" list="incCities" placeholder="Vantaa, Helsinki, Espoo…"><datalist id="incCities"><option>Vantaa</option><option>Helsinki</option><option>Espoo</option><option>Tampere</option></datalist></div><div class="question"><label>What do they mainly need?</label><select id="incMain" class="intake-select"><option value="">Choose</option><option>Carruur iyo skuul</option><option>Shaqo</option><option>Waxbarasho</option><option>Arrin kale</option></select></div><div class="question hidden" id="incAgeWrap"><label>Child stage</label><select id="incAge" class="intake-select"><option value="">Not sure</option><option value="under7">Daycare or preschool</option><option value="over7">School-age</option></select></div><div class="question"><label>What specifically?</label><select id="incSub" class="intake-select" disabled><option value="">Choose the main need first</option></select><p class="intake-hint">Ask this while you are on the call. It completes the short intake before the first interview; it is not an eligibility decision.</p></div><div id="incErr" class="intake-error"></div><button class="btn primary" id="incSave" type="button" style="width:100%;padding:14px">Save &amp; start first interview</button></div>';document.body.appendChild(el);
$('incClose').onclick=close;$('incMain').onchange=renderSubs;$('incSave').onclick=save;el.addEventListener('click',e=>{if(e.target===el)close()});}
function renderSubs(){const main=$('incMain').value,list=SUBS[main]||[];$('incSub').disabled=!list.length;$('incSub').innerHTML=list.length?'<option value="">Choose</option>'+list.map(x=>'<option>'+esc(x)+'</option>').join(''):'<option value="">Choose the main need first</option>';$('incAgeWrap').classList.toggle('hidden',main!=='Carruur iyo skuul')}
function open(contact){ensureUI();active=contact;$('incName').textContent='Finish request · '+(contact.name||'Family');$('incMeta').textContent=contact.phone||'';$('incCity').value=contact.city||'';$('incMain').value=contact.main_need||'';renderSubs();if(contact.sub_need)$('incSub').value=contact.sub_need;if(contact.age_group)$('incAge').value=contact.age_group;$('incErr').textContent='';$('incompleteDrawer').classList.remove('hidden');document.body.style.overflow='hidden';setTimeout(()=>$('incCity').focus(),60)}
function close(){$('incompleteDrawer')?.classList.add('hidden');document.body.style.overflow='';active=null}
async function save(){if(!active)return;const city=$('incCity').value.trim(),main=$('incMain').value,sub=$('incSub').value,age=main==='Carruur iyo skuul'?$('incAge').value:'';if(!city||!main||!sub){$('incErr').textContent='Add the city, main need and specific need first.';return}const btn=$('incSave');btn.disabled=true;btn.textContent='Saving…';$('incErr').textContent='';try{const result=await api({action:'complete',id:active.id,city,main_need:main,sub_need:sub,age_group:age||null});close();if(result.lead_id&&typeof window.openInterview==='function')window.openInterview(result.lead_id);window.dispatchEvent(new Event('dataUpdated'));const refresh=$('refresh');if(refresh)refresh.click()}catch(e){$('incErr').textContent=e.message||'Could not save.'}finally{btn.disabled=false;btn.textContent='Save & start first interview'}}
async function remove(contact,onDone){if(!confirm('Delete the unfinished intake for '+(contact.name||'this contact')+'? This removes the saved contact details and cannot be undone. Anonymous funnel counts stay intact.'))return;try{await api({action:'delete',id:contact.id});window.dispatchEvent(new Event('dataUpdated'));const refresh=$('refresh');if(refresh)refresh.click();if(onDone)onDone()}catch(e){alert(e.message||'Could not delete this unfinished intake.')}}
async function assign(contact,operatorId,onDone){try{await api({action:'assign',id:contact.id,operator_id:operatorId});window.dispatchEvent(new Event('dataUpdated'));const refresh=$('refresh');if(refresh)refresh.click();if(onDone)onDone()}catch(e){alert(e.message||'Could not assign this intake.')}}
async function createContactCase(contact,operatorId){if(!contact?.id)throw Error('Missing intake contact.');const result=await api({action:'create_contact_case',id:contact.id,operator_id:operatorId||null});if(!result.lead_id)throw Error('Could not create a contact case.');window.dispatchEvent(new Event('dataUpdated'));const refresh=$('refresh');if(refresh)refresh.click();return result.lead_id}
// Called directly by the queue UI (crm-queue-navigation.js) with the partial
// record it already has in memory — no separate fetch/sync needed here.
window.AqoonIncompleteIntake={open,remove,assign,createContactCase};
})();
