(()=>{'use strict';
const END='https://qxracwbsyfibcelasxbs.supabase.co/functions/v1/family-incomplete-admin';
const $=id=>document.getElementById(id);
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const SUBS={
  'Carruurta':['Xannaano ama päiväkoti','Esiopetus','Ciyaaro iyo hiwaayado','Dugsiga iyo taageerada ilmaha','Codsi ama diiwaangelin','Wax kale'],
  'Shaqo':['Shaqo raadis ama codsi shaqo','Kaararka iyo shahaadooyinka shaqada','Barnaamij shaqo ama tababar','Bilaabidda ganacsi','Wax kale'],
  'Waxbarasho':['Baro Finnish ama hel koorso','YKI ama heerka Finnish-ka','Dhammaystir waxbarasho ama hel shahaadadaada ugu horreysa','Waxbarasho ama barnaamij kale','Wax kale'],
  'Barnaamijyo':['Barnaamij ama hanke','Adeeg ama taageero kale','Ma hubo waxa la yiraahdo','Wax kale']
};
let contacts=[],active=null;
function pw(){return sessionStorage.getItem('aqoon_tracker_password')||''}
async function api(body){const r=await fetch(END,{method:'POST',headers:{'Content-Type':'application/json','x-tracker-password':pw()},body:JSON.stringify(body),cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||d.error||'Request failed');return d}
function ensureUI(){if($('incompleteDrawer'))return;const style=document.createElement('style');style.textContent='.intake-select{width:100%;min-height:52px;border:1px solid #e4dfd3;border-radius:16px;background:#fff;padding:10px 12px;font:inherit;color:#123554}.intake-error{color:#a33a32;font-size:13px;margin-top:8px}.intake-hint{font-size:12px;color:#687281;margin:5px 0 0}';document.head.appendChild(style);
const el=document.createElement('section');el.id='incompleteDrawer';el.className='drawer hidden';el.innerHTML='<div class="drawer-card"><div class="drawer-top"><div><h2 id="incName">Finish request</h2><small class="muted" id="incMeta"></small></div><button class="btn secondary" id="incClose" type="button">Close</button></div><div class="question"><label>City</label><input id="incCity" list="incCities" placeholder="Vantaa, Helsinki, Espoo…"><datalist id="incCities"><option>Vantaa</option><option>Helsinki</option><option>Espoo</option><option>Tampere</option></datalist></div><div class="question"><label>What do they mainly need?</label><select id="incMain" class="intake-select"><option value="">Choose</option><option>Carruurta</option><option>Shaqo</option><option>Waxbarasho</option><option>Barnaamijyo</option></select></div><div class="question hidden" id="incAgeWrap"><label>Child age group</label><select id="incAge" class="intake-select"><option value="">Not sure</option><option value="under7">Under 7</option><option value="7-15">7–15</option><option value="16plus">16+</option></select></div><div class="question"><label>What specifically?</label><select id="incSub" class="intake-select" disabled><option value="">Choose the main need first</option></select><p class="intake-hint">Ask this while you are on the call. This completes the short intake before the first interview.</p></div><div id="incErr" class="intake-error"></div><button class="btn primary" id="incSave" type="button" style="width:100%;padding:14px">Save & start first interview</button></div>';document.body.appendChild(el);
$('incClose').onclick=close;$('incMain').onchange=renderSubs;$('incSave').onclick=save;el.addEventListener('click',e=>{if(e.target===el)close()});}
function renderSubs(){const main=$('incMain').value,list=SUBS[main]||[];$('incSub').disabled=!list.length;$('incSub').innerHTML=list.length?'<option value="">Choose</option>'+list.map(x=>'<option>'+esc(x)+'</option>').join(''):'<option value="">Choose the main need first</option>';$('incAgeWrap').classList.toggle('hidden',main!=='Carruurta')}
function open(contact){ensureUI();active=contact;$('incName').textContent='Finish request · '+(contact.name||'Family');$('incMeta').textContent=contact.phone||'';$('incCity').value=contact.city||'';$('incMain').value=contact.main_need||'';renderSubs();if(contact.sub_need)$('incSub').value=contact.sub_need;if(contact.age_group)$('incAge').value=contact.age_group;$('incErr').textContent='';$('incompleteDrawer').classList.remove('hidden');document.body.style.overflow='hidden';setTimeout(()=>$('incCity').focus(),60)}
function close(){$('incompleteDrawer')?.classList.add('hidden');document.body.style.overflow='';active=null}
async function save(){if(!active)return;const city=$('incCity').value.trim(),main=$('incMain').value,sub=$('incSub').value,age=main==='Carruurta'?$('incAge').value:'';if(!city||!main||!sub){$('incErr').textContent='Add the city, main need and specific need first.';return}const btn=$('incSave');btn.disabled=true;btn.textContent='Saving…';$('incErr').textContent='';try{await api({action:'complete',id:active.id,city,main_need:main,sub_need:sub,age_group:age||null});close();const refresh=$('refresh');if(refresh){refresh.click();await new Promise(r=>setTimeout(r,500))}if(typeof openInterview==='function'){openInterview(active.id)}}catch(e){$('incErr').textContent=e.message||'Could not save.'}finally{btn.disabled=false;btn.textContent='Save & start first interview'}}
async function remove(contact,button){if(!confirm('Delete the unfinished intake for '+(contact.name||'this contact')+'? This removes the saved contact details and cannot be undone. Anonymous funnel counts stay intact.'))return;button.disabled=true;button.textContent='Deleting…';try{await api({action:'delete',id:contact.id});contacts=contacts.filter(x=>x.id!==contact.id);$('refresh')?.click();setTimeout(sync,250)}catch(e){alert(e.message||'Could not delete this unfinished intake.');button.disabled=false;button.textContent='Delete'}}
async function openFirstInterview(phone){for(let i=0;i<12;i++){await new Promise(r=>setTimeout(r,350));const cards=[...document.querySelectorAll('#leadList .lead')],card=cards.find(c=>c.querySelector('a.phone')?.textContent.trim()===String(phone||'').trim());if(card){card.querySelector('.lead-summary')?.click();setTimeout(()=>card.querySelector('[data-interview]')?.click(),80);return}}}
function addButtons(){ensureUI();const host=$('partials');if(!host)return;const cards=[...host.querySelectorAll('.lead')];cards.forEach(card=>{if(card.dataset.finishReady==='1')return;const tel=card.querySelector('a[href^="tel:"]'),phone=tel?.getAttribute('href')?.slice(4)||'',name=card.querySelector('h3')?.textContent.trim()||'',contact=contacts.find(x=>String(x.phone||'')===phone&&String(x.name||'').trim()===name)||contacts.find(x=>String(x.phone||'')===phone);if(!contact)return;card.dataset.finishReady='1';const summary=card.querySelector('.lead-summary');if(!summary)return;const call=summary.querySelector('a.btn');if(call){const wrap=document.createElement('div');wrap.className='partial-actions';call.parentNode.insertBefore(wrap,call);wrap.appendChild(call);call.classList.add('partial-call');const b=document.createElement('button');b.type='button';b.className='btn teal partial-finish';b.textContent='Finish';b.setAttribute('aria-label','Finish intake for '+name);b.onclick=()=>open(contact);wrap.appendChild(b);const del=document.createElement('button');del.type='button';del.className='partial-delete';del.textContent='Delete';del.setAttribute('aria-label','Delete unfinished intake for '+name);del.onclick=()=>remove(contact,del);wrap.appendChild(del)}})}
async function sync(){if(!pw())return;try{contacts=(await api({action:'list'})).contacts||[];addButtons()}catch(_){}}
const observer=new MutationObserver(()=>addButtons());function start(){ensureUI();const host=$('partials');if(host)observer.observe(host,{childList:true,subtree:true});sync();document.addEventListener('click',e=>{if(e.target.closest('#refresh,.tab[data-tab="crm"]'))setTimeout(sync,250)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
