(()=>{
const END="https://qxracwbsyfibcelasxbs.supabase.co/functions/v1/ops-admin";
const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const stages=["lead","contacted","discovery","proposal_sent","decision_review","won","delivery","expansion","closed_lost"];
const labels={lead:"Lead",contacted:"Contacted",discovery:"Discovery",proposal_sent:"Proposal sent",decision_review:"Decision review",won:"Won",delivery:"Delivery",expansion:"Expansion",closed_lost:"Closed lost"};
let data={opportunities:[],activities:[],events:[],family_followups:[]},filter="all",mode="",record=null,loading=false;
function password(){return sessionStorage.getItem("aqoon_tracker_password")||""}
async function api(body){const r=await fetch(END,{method:"POST",headers:{"Content-Type":"application/json","x-tracker-password":password()},body:JSON.stringify(body),cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.error||"Operations request failed");return d}
function fail(e){const box=$("#err");if(box){box.textContent=e.message||String(e);box.classList.remove("hidden")}else alert(e.message||e)}
function dt(v){if(!v)return"";const d=new Date(v);return Number.isNaN(d.getTime())?"":new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Helsinki",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}).format(d)}
function local(v){if(!v)return"";const d=new Date(v);return Number.isNaN(d.getTime())?"":new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function priority(o){if(!o.next_action_at)return 1;const t=new Date(o.next_action_at).getTime(),now=Date.now();if(t<now)return 0;if(t-now<86400000)return .5;return 2}
function progress(stage){const path=["lead","contacted","discovery","proposal_sent","decision_review","won","delivery","expansion"],i=path.indexOf(stage);return path.map((_,n)=>`<i class="${n<=i?"done":""}"></i>`).join("")}
function renderSales(){
  const active=data.opportunities.filter(x=>x.stage!=="closed_lost"),overdue=active.filter(x=>x.next_action_at&&new Date(x.next_action_at)<new Date()).length,noAction=active.filter(x=>!x.next_action||!x.next_action_at).length;
  $("#salesHealth").innerHTML=`<div><strong>${active.length}</strong><span>active relationships</span></div><div><strong>${overdue}</strong><span>overdue actions</span></div><div><strong>${noAction}</strong><span>without next action</span></div>`;
  const counts=Object.fromEntries(stages.map(s=>[s,data.opportunities.filter(x=>x.stage===s).length]));
  $("#salesStageFilter").innerHTML=`<button class="${filter==="all"?"on":""}" data-sales-filter="all">All ${data.opportunities.length}</button>`+stages.filter(s=>counts[s]).map(s=>`<button class="${filter===s?"on":""}" data-sales-filter="${s}">${labels[s]} ${counts[s]}</button>`).join("");
  const list=data.opportunities.filter(x=>filter==="all"||x.stage===filter).sort((a,b)=>priority(a)-priority(b)||String(b.updated_at).localeCompare(String(a.updated_at)));
  $("#salesPipeline").innerHTML=list.map(o=>`<article class="opportunity" data-opp="${esc(o.id)}"><div class="opp-top"><div><h3>${esc(o.organization)}</h3><div class="opp-contact">${esc([o.contact_name,o.contact_role].filter(Boolean).join(" · ")||o.source||"AQOON relationship")}</div></div><span class="stage-pill ${esc(o.health)}">${esc(labels[o.stage]||o.stage)}</span></div><p class="opp-summary">${esc(o.summary||"Add the relationship context and decision status.")}</p><div class="next-action-box"><div><span>NEXT ACTION</span><strong>${esc(o.next_action||"Set a next action")}</strong></div><time>${esc(o.next_action_at?dt(o.next_action_at):"No date")}</time></div><div class="opp-progress">${progress(o.stage)}</div></article>`).join("")||'<div class="empty">No opportunities in this stage.</div>';
  document.querySelectorAll("[data-sales-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.salesFilter;renderSales()});
  document.querySelectorAll("[data-opp]").forEach(x=>x.onclick=()=>openOpportunity(data.opportunities.find(o=>o.id===x.dataset.opp)));
}
function eventRows(){
  const now=Date.now()-86400000;
  const normal=data.events.filter(x=>x.status==="planned"&&new Date(x.starts_at).getTime()>=now).map(x=>({...x,source_kind:"event"}));
  const family=data.family_followups.filter(x=>new Date(x.next_follow_up_at).getTime()>=now).map(x=>({id:x.id,title:`Follow up · ${x.name}`,event_type:"call",starts_at:x.next_follow_up_at,notes:[x.city,x.main_need].filter(Boolean).join(" · "),source_kind:"family"}));
  const sales=data.opportunities.filter(o=>o.stage!=="closed_lost"&&o.next_action_at&&new Date(o.next_action_at).getTime()>=now&&!normal.some(e=>e.opportunity_id===o.id&&Math.abs(new Date(e.starts_at)-new Date(o.next_action_at))<43200000)).map(o=>({id:o.id,title:o.next_action||`Next action · ${o.organization}`,event_type:"task",starts_at:o.next_action_at,notes:o.organization,source_kind:"sales"}));
  return [...normal,...family,...sales].sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at)).slice(0,8)
}
function renderAgenda(){const rows=eventRows();$("#agendaList").innerHTML=rows.map(x=>{const d=new Date(x.starts_at),day=new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Helsinki",weekday:"short"}).format(d),date=new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Helsinki",day:"numeric",month:"short"}).format(d);return `<div class="agenda-item" data-event="${x.source_kind==="event"?esc(x.id):""}"><div class="agenda-when"><strong>${esc(day)}</strong>${esc(date)}</div><div><h4>${esc(x.title)}</h4><p>${esc(x.notes||dt(x.starts_at))}</p></div><span class="agenda-kind ${esc(x.event_type)}">${esc(x.event_type)}</span></div>`}).join("")||'<div class="empty">No upcoming calls or meetings. Add the next commitment now.</div>';document.querySelectorAll("[data-event]:not([data-event=''])").forEach(x=>x.onclick=()=>openEvent(data.events.find(e=>e.id===x.dataset.event)))}
async function load(force=false){if(loading||!password())return;if(!force&&data.opportunities.length)return;loading=true;try{data=await api({action:"list"});renderSales();renderAgenda()}catch(e){fail(e)}finally{loading=false}}
function field(name,label,value="",type="text",full=false,options=[]){if(type==="select")return `<div class="ops-field ${full?"full":""}"><label>${label}</label><select name="${name}">${options.map(x=>`<option value="${x}" ${x===value?"selected":""}>${esc(labels[x]||x.replaceAll("_"," "))}</option>`).join("")}</select></div>`;if(type==="textarea")return `<div class="ops-field ${full?"full":""}"><label>${label}</label><textarea name="${name}">${esc(value)}</textarea></div>`;return `<div class="ops-field ${full?"full":""}"><label>${label}</label><input name="${name}" type="${type}" value="${esc(value)}"></div>`}
function showDialog(){$("#opsDialog").classList.remove("hidden");document.body.style.overflow="hidden"}
function closeDialog(){$("#opsDialog").classList.add("hidden");document.body.style.overflow="";record=null}
function openOpportunity(o=null){mode="opportunity";record=o;$("#opsDialogTitle").textContent=o?o.organization:"New sales lead";$("#opsDialogHint").textContent="The card should answer: where is this going, why, and what happens next?";$("#deleteOpsRecord").classList.toggle("hidden",!o);const activities=o?data.activities.filter(a=>a.opportunity_id===o.id):[];$("#opsFormBody").innerHTML=`<div class="ops-grid">${field("organization","Organisation",o?.organization||"")}${field("contact_name","Contact",o?.contact_name||"")}${field("contact_role","Contact role",o?.contact_role||"")}${field("source","Relationship source",o?.source||"")}${field("stage","Stage",o?.stage||"lead","select",false,stages)}${field("health","Health",o?.health||"on_track","select",false,["on_track","waiting","at_risk","blocked"])}${field("probability","Probability %",o?.probability??"","number")}${field("next_action_at","Next action date",local(o?.next_action_at),"datetime-local")}${field("summary","What is happening now?",o?.summary||"","textarea",true)}${field("goal","Goal",o?.goal||"","textarea",true)}${field("success_definition","What does success mean?",o?.success_definition||"","textarea",true)}${field("completed_steps","Completed — one per line",(o?.completed_steps||[]).join("\n"),"textarea",true)}${field("next_steps","Next steps — one per line",(o?.next_steps||[]).join("\n"),"textarea",true)}${field("next_action","One concrete next action",o?.next_action||"","textarea",true)}</div>${o?`<div class="ops-timeline"><h3>Relationship timeline</h3>${activities.map(a=>`<div class="timeline-row"><i></i><div><strong>${esc(a.title)}</strong><small>${esc(a.activity_type)} · ${esc(dt(a.happened_at||a.due_at||a.created_at))}${a.notes?" · "+esc(a.notes):""}</small></div></div>`).join("")||'<div class="empty">No activities yet.</div>'}<div class="ops-grid">${field("activity_title","Log an email, call, meeting or note")}${field("activity_type","Type","note","select",false,["email","call","meeting","proposal","report","note","task"])}${field("activity_notes","Activity notes","","textarea",true)}</div><button class="btn secondary" id="addActivity" type="button">Add to timeline</button></div>`:""}`;showDialog();if(o)$("#addActivity").onclick=addActivity}
function openEvent(e=null){mode="event";record=e;$("#opsDialogTitle").textContent=e?"Edit calendar item":"Add call or meeting";$("#opsDialogHint").textContent="Anything with a date should become visible work.";$("#deleteOpsRecord").classList.toggle("hidden",!e);const relationship=`<div class="ops-field"><label>Sales relationship (optional)</label><select name="opportunity_id"><option value="">General AQOON event</option>${data.opportunities.map(o=>`<option value="${esc(o.id)}" ${e?.opportunity_id===o.id?"selected":""}>${esc(o.organization)}</option>`).join("")}</select></div>`;$("#opsFormBody").innerHTML=`<div class="ops-grid">${field("title","Title",e?.title||"")}${field("event_type","Type",e?.event_type||"meeting","select",false,["call","meeting","deadline","task"])}${field("starts_at","Starts",local(e?.starts_at),"datetime-local")}${field("ends_at","Ends",local(e?.ends_at),"datetime-local")}${field("status","Status",e?.status||"planned","select",false,["planned","done","cancelled"])}${relationship}${field("notes","Notes",e?.notes||"","textarea",true)}</div>`;showDialog()}
function form(){return Object.fromEntries(new FormData($("#opsForm")).entries())}
async function save(e){e.preventDefault();const v=form();$("#saveOpsRecord").disabled=true;try{if(mode==="opportunity"){await api({action:"save_opportunity",id:record?.id,...v,probability:v.probability===""?null:Number(v.probability),completed_steps:v.completed_steps.split("\n").map(x=>x.trim()).filter(Boolean),next_steps:v.next_steps.split("\n").map(x=>x.trim()).filter(Boolean),next_action_at:v.next_action_at?new Date(v.next_action_at).toISOString():null})}else await api({action:"save_event",id:record?.id,...v,starts_at:v.starts_at?new Date(v.starts_at).toISOString():null,ends_at:v.ends_at?new Date(v.ends_at).toISOString():null});closeDialog();data.opportunities=[];await load(true)}catch(x){fail(x)}finally{$("#saveOpsRecord").disabled=false}}
async function remove(){if(!record)return;const what=mode==="opportunity"?record.organization:record.title;if(!confirm(`Delete ${what}? This cannot be undone.`))return;try{await api({action:mode==="opportunity"?"delete_opportunity":"delete_event",id:record.id});closeDialog();data.opportunities=[];await load(true)}catch(e){fail(e)}}
async function addActivity(){const v=form();if(!v.activity_title)return alert("Add an activity title first.");try{await api({action:"add_activity",opportunity_id:record.id,title:v.activity_title,activity_type:v.activity_type,notes:v.activity_notes,happened_at:new Date().toISOString(),completed_at:new Date().toISOString()});data.opportunities=[];await load(true);openOpportunity(data.opportunities.find(x=>x.id===record.id))}catch(e){fail(e)}}
function start(){
  $("#addOpportunity").onclick=()=>openOpportunity();$("#addAgendaEvent").onclick=()=>openEvent();$("#closeOpsDialog").onclick=closeDialog;$("#opsForm").onsubmit=save;$("#deleteOpsRecord").onclick=remove;
  document.addEventListener("click",e=>{if(e.target.closest('[data-tab="sales"]'))setTimeout(()=>load(true),100);if(e.target.closest("#refresh"))setTimeout(()=>load(true),150)});
  const obs=new MutationObserver(()=>{if(!$("#app").classList.contains("hidden"))load()});obs.observe($("#app"),{attributes:true,attributeFilter:["class"]});if(!$("#app").classList.contains("hidden"))load();
}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",start):start();
})();
