(()=>{'use strict';
const $=id=>document.getElementById(id);
function nav(){const items={dashboard:['⌂','Today'],crm:['♡','Families'],analytics:['↗','Analytics'],sales:['◎','Sales']};Object.entries(items).forEach(([key,value])=>{const b=document.querySelector('.tab[data-tab="'+key+'"]');if(b)b.innerHTML='<span>'+value[0]+'</span>'+value[1]})}
function enhanceFunnel(){const rows=[...document.querySelectorAll('#fullFunnel .frow')];if(!rows.length)return;rows.forEach(r=>r.querySelectorAll('.drop-note').forEach(x=>x.remove()));const vals=rows.map(r=>Number(r.querySelector('strong')?.textContent)||0);rows.forEach((r,i)=>{if(i>=rows.length-1)return;const from=vals[i],to=vals[i+1],lost=Math.max(0,from-to),rate=from?Math.round(lost/from*100):0;const d=document.createElement('div');d.className='drop-note '+(!lost?'neutral':'');d.textContent=lost?'-'+lost+' lost · '+rate+'%':'no loss';r.appendChild(d)});enhanceTraffic()}
function enhanceTraffic(){const cols=[...document.querySelectorAll('#trafficChart .tcol')];if(!cols.length)return;let best=null,bestN=-1;cols.forEach(c=>{const m=(c.getAttribute('title')||'').match(/:\s*(\d+)\s+sessions/i),n=m?Number(m[1]):0;if(n>bestN){bestN=n;best=c}});const peak=$('trafficPeak');if(peak&&best){const label=best.querySelector('small')?.textContent||'';peak.textContent='peak '+label}}
function controls(){document.querySelectorAll('#periodSwitch [data-days]').forEach(b=>b.onclick=()=>{const d=b.dataset.days,sel=$('days');if(!sel)return;sel.value=d;document.querySelectorAll('#periodSwitch button').forEach(x=>x.classList.toggle('on',x===b));sel.dispatchEvent(new Event('change',{bubbles:true}))});document.querySelectorAll('.breakdown-tabs [data-breakdown]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.breakdown-tabs button').forEach(x=>x.classList.toggle('on',x===b));document.querySelectorAll('.breakdown-pane').forEach(p=>p.classList.toggle('hidden',p.dataset.pane!==b.dataset.breakdown))})}
function watch(){const funnel=$('fullFunnel'),traffic=$('trafficChart');if(funnel)new MutationObserver(ms=>{if(ms.some(m=>[...m.addedNodes].some(n=>n.nodeType===1&&(n.matches?.('.frow')||n.querySelector?.('.frow')))))requestAnimationFrame(enhanceFunnel)}).observe(funnel,{childList:true});if(traffic)new MutationObserver(()=>requestAnimationFrame(enhanceTraffic)).observe(traffic,{childList:true})}
nav();controls();watch();setTimeout(()=>{enhanceFunnel();enhanceTraffic()},500);
})();
