-- Promote only current, primary-source routes discovered in the legacy chunk
-- corpus. The chunks remain untouched and discovery-only.

with source_rows(source_key,publisher,authority_level,canonical_url,title,scope,volatility,recheck_after,notes) as (
  values
    ('src.espoo.free-early-childhood-education-five-year-olds','City of Espoo','official_primary','https://www.espoo.fi/en/childcare-and-education/early-childhood-education/free-early-childhood-education-five-year-olds','Free early childhood education for five-year-olds','Espoo; children turning five this calendar year','medium',now()+interval '30 days','Verified against the current City of Espoo page on 2026-08-30; discovered through municipal_knowledge_chunks.'),
    ('src.vantaa.hobby-support-children-and-youth','City of Vantaa','official_primary','https://www.vantaa.fi/en/hobby-support-children-and-youth','Hobby Support for Children and Youth','Vantaa; low-income households; children and young people aged 7–17','live',now()+interval '7 days','Verified against the current City of Vantaa page on 2026-08-30; application availability must be rechecked before action; discovered through municipal_knowledge_chunks.'),
    ('src.oph.esiopetus-learning-participation-support','Finnish National Agency for Education','official_primary','https://www.oph.fi/fi/koulutus-ja-tutkinnot/esiopetus/oppimisen-ja-esiopetukseen-osallistumisen-tuki','Oppimisen ja esiopetukseen osallistumisen tuki','Finland; pre-primary education','medium',now()+interval '60 days','Verified against the current OPH page on 2026-08-30; the local education organiser decides the arrangement; discovered through oph_knowledge_chunks.'),
    ('src.oph.hoks','Finnish National Agency for Education','official_primary','https://www.oph.fi/fi/koulutus-ja-tutkinnot/henkilokohtaistaminen','Henkilökohtainen osaamisen kehittämissuunnitelma (HOKS)','Finland; vocational education students','medium',now()+interval '60 days','Verified against the current OPH page on 2026-08-30; the vocational education provider prepares and updates the plan; discovered through oph_knowledge_chunks.')
), upsert_sources as (
  insert into public.knowledge_sources (source_key,publisher,authority_level,canonical_url,title,scope,volatility,verification_state,last_checked_at,recheck_after,notes)
  select source_key,publisher,authority_level,canonical_url,title,scope,volatility,'verified',now(),recheck_after,notes from source_rows
  on conflict (source_key) do update set publisher=excluded.publisher,authority_level=excluded.authority_level,canonical_url=excluded.canonical_url,title=excluded.title,scope=excluded.scope,volatility=excluded.volatility,verification_state='verified',last_checked_at=now(),recheck_after=excluded.recheck_after,notes=excluded.notes,updated_at=now()
  returning id,source_key,recheck_after
), service_rows(service_key,name_fi,name_so,authority_name,decision_maker,scope,source_key,matching_fields) as (
  values
    ('service.espoo.free-early-childhood-education-five-year-olds','Maksuton varhaiskasvatus viisivuotiaille','Varhaiskasvatus bilaash ah oo loogu talagalay carruurta shan jirka noqonaya','City of Espoo','City of Espoo', 'Espoo; children turning five this calendar year','src.espoo.free-early-childhood-education-five-year-olds','["city","child_age_or_birth_date","desired_start_date","care_need_schedule"]'::jsonb),
    ('service.vantaa.hobby-support-children-and-youth','Harrastustuki lapsille ja nuorille','Taageerada harrastus-ka ee carruurta iyo dhalinyarada','City of Vantaa','City of Vantaa','Vantaa; low-income households; children and young people aged 7–17','src.vantaa.hobby-support-children-and-youth','["city","school_age_or_grade","household_income_context","hobby_support_need"]'::jsonb),
    ('service.finland.esiopetus-learning-participation-support','Oppimisen ja esiopetukseen osallistumisen tuki','Taageerada waxbarashada iyo ka qaybgalka esiopetus','Finnish National Agency for Education / local education organiser','Local pre-primary education organiser','Finland; pre-primary education','src.oph.esiopetus-learning-participation-support','["city","care_goal","support_need_description"]'::jsonb),
    ('service.finland.vocational-hoks','Henkilökohtainen osaamisen kehittämissuunnitelma (HOKS)','Qorshaha shakhsiga ah ee horumarinta aqoonta (HOKS)','Finnish National Agency for Education / vocational education provider','Vocational education provider','Finland; vocational education students','src.oph.hoks','["current_study","education_support_need"]'::jsonb)
), upsert_services as (
  insert into public.knowledge_services (service_key,name_fi,name_so,authority_name,decision_maker,scope,verification_state,source_ids,matching_fields,last_verified_at,recheck_after)
  select sr.service_key,sr.name_fi,sr.name_so,sr.authority_name,sr.decision_maker,sr.scope,'verified',array[s.id],sr.matching_fields,now(),s.recheck_after
  from service_rows sr join upsert_sources s using(source_key)
  on conflict (service_key) do update set name_fi=excluded.name_fi,name_so=excluded.name_so,authority_name=excluded.authority_name,decision_maker=excluded.decision_maker,scope=excluded.scope,verification_state='verified',source_ids=excluded.source_ids,matching_fields=excluded.matching_fields,last_verified_at=now(),recheck_after=excluded.recheck_after,updated_at=now()
  returning id,service_key
), route_rows(route_key,service_key,need_domain,scope,required_inputs,blocking_inputs,steps,source_key,volatility) as (
  values
    ('route.espoo.free-early-childhood-education-five-year-olds','service.espoo.free-early-childhood-education-five-year-olds','daycare','{"city":"Espoo","child_age":"turning_five_this_year"}'::jsonb,'["city","child_age_or_birth_date","desired_start_date","care_need_schedule"]'::jsonb,'["city_not_espoo","child_not_turning_five_this_year"]'::jsonb,'["Confirm the child turns five this calendar year and the care hours needed.","Use Espoo eVaka or the current City of Espoo application route; the city confirms the place and arrangement."]'::jsonb,'src.espoo.free-early-childhood-education-five-year-olds','medium'),
    ('route.vantaa.hobby-support-children-and-youth','service.vantaa.hobby-support-children-and-youth','hobby','{"city":"Vantaa","age_range":"7-17","income_context":"low_income"}'::jsonb,'["city","school_age_or_grade","household_income_context","hobby_support_need"]'::jsonb,'["city_not_vantaa","outside_age_range","household_income_not_low","not_paid_guided_hobby"]'::jsonb,'["Confirm the child is 7–17, lives in Vantaa and a paid guided hobby is the issue.","Open the current City of Vantaa hobby-support page and confirm the application window and documents before helping the family apply."]'::jsonb,'src.vantaa.hobby-support-children-and-youth','live'),
    ('route.finland.esiopetus-learning-participation-support','service.finland.esiopetus-learning-participation-support','daycare','{"country":"Finland","education_stage":"esiopetus"}'::jsonb,'["city","care_goal","support_need_description"]'::jsonb,'["not_in_esiopetus","support_need_not_described"]'::jsonb,'["Clarify the child’s current or planned esiopetus and what participation or learning support needs to be discussed.","Help the family prepare questions for the local esiopetus organiser; the organiser assesses and decides the support arrangement."]'::jsonb,'src.oph.esiopetus-learning-participation-support','medium'),
    ('route.finland.vocational-hoks','service.finland.vocational-hoks','education','{"country":"Finland","education_stage":"vocational"}'::jsonb,'["current_study","education_support_need"]'::jsonb,'["not_in_vocational_education"]'::jsonb,'["Confirm the person is starting or studying vocational education and the individual-plan issue they want to discuss.","Prepare questions for the education provider; the provider creates and updates the HOKS with the student."]'::jsonb,'src.oph.hoks','medium')
), upsert_routes as (
  insert into public.knowledge_routes (route_key,service_id,need_domain,scope,required_inputs,blocking_inputs,steps,source_ids,verification_state,volatility,last_verified_at,recheck_after)
  select rr.route_key,sv.id,rr.need_domain,rr.scope,rr.required_inputs,rr.blocking_inputs,rr.steps,array[s.id],'verified',rr.volatility,now(),s.recheck_after
  from route_rows rr join upsert_services sv using(service_key) join upsert_sources s using(source_key)
  on conflict (route_key) do update set service_id=excluded.service_id,need_domain=excluded.need_domain,scope=excluded.scope,required_inputs=excluded.required_inputs,blocking_inputs=excluded.blocking_inputs,steps=excluded.steps,source_ids=excluded.source_ids,verification_state='verified',volatility=excluded.volatility,last_verified_at=now(),recheck_after=excluded.recheck_after,updated_at=now()
  returning id,route_key
), criterion_rows(criterion_key,route_key,label,criterion_type,field_key,rule_json,source_key) as (
  values
    ('criterion.espoo.free-ece-five.city','route.espoo.free-early-childhood-education-five-year-olds','Family lives in Espoo','required','city','{"expected":"Espoo"}'::jsonb,'src.espoo.free-early-childhood-education-five-year-olds'),
    ('criterion.espoo.free-ece-five.age','route.espoo.free-early-childhood-education-five-year-olds','Child turns five during the current calendar year','required','child_age_or_birth_date','{"must_confirm":"turning_five_this_year"}'::jsonb,'src.espoo.free-early-childhood-education-five-year-olds'),
    ('criterion.espoo.free-ece-five.schedule','route.espoo.free-early-childhood-education-five-year-olds','Care schedule and desired start need City of Espoo confirmation','authority_confirmation','care_need_schedule','{"published_offer":"20 hours per week; exact arrangement confirmed by provider/city"}'::jsonb,'src.espoo.free-early-childhood-education-five-year-olds'),
    ('criterion.vantaa.hobby-support.city','route.vantaa.hobby-support-children-and-youth','Family lives in Vantaa','required','city','{"expected":"Vantaa"}'::jsonb,'src.vantaa.hobby-support-children-and-youth'),
    ('criterion.vantaa.hobby-support.age','route.vantaa.hobby-support-children-and-youth','Child or young person is in the published 7–17 age range','required','school_age_or_grade','{"must_confirm":"age_7_to_17"}'::jsonb,'src.vantaa.hobby-support-children-and-youth'),
    ('criterion.vantaa.hobby-support.income','route.vantaa.hobby-support-children-and-youth','Low-income context makes the paid hobby difficult','required','household_income_context','{"must_confirm":true,"no_aqoon_income_decision":true}'::jsonb,'src.vantaa.hobby-support-children-and-youth'),
    ('criterion.vantaa.hobby-support.availability','route.vantaa.hobby-support-children-and-youth','Application window, eligible hobby and documents must be confirmed','authority_confirmation','hobby_support_need','{"must_confirm":true}'::jsonb,'src.vantaa.hobby-support-children-and-youth'),
    ('criterion.finland.esiopetus-support.stage','route.finland.esiopetus-learning-participation-support','Child is in or entering esiopetus','required','care_goal','{"expected_any":["Esiopetus","Esiopetus + daycare"]}'::jsonb,'src.oph.esiopetus-learning-participation-support'),
    ('criterion.finland.esiopetus-support.local-decision','route.finland.esiopetus-learning-participation-support','Local education organiser assesses the support arrangement','authority_confirmation','support_need_description','{"must_confirm":true,"no_aqoon_decision":true}'::jsonb,'src.oph.esiopetus-learning-participation-support'),
    ('criterion.finland.vocational-hoks.stage','route.finland.vocational-hoks','Person is starting or studying vocational education','required','current_study','{"expected":"Vocational"}'::jsonb,'src.oph.hoks'),
    ('criterion.finland.vocational-hoks.provider','route.finland.vocational-hoks','Education provider prepares and updates the individual plan with the student','authority_confirmation','education_support_need','{"must_confirm":true,"no_aqoon_decision":true}'::jsonb,'src.oph.hoks')
)
insert into public.knowledge_criteria (criterion_key,route_id,label,criterion_type,field_key,rule_json,source_ids,verification_state,last_verified_at,recheck_after)
select cr.criterion_key,r.id,cr.label,cr.criterion_type,cr.field_key,cr.rule_json,array[s.id],'verified',now(),s.recheck_after
from criterion_rows cr join upsert_routes r using(route_key) join upsert_sources s using(source_key)
on conflict (criterion_key) do update set route_id=excluded.route_id,label=excluded.label,criterion_type=excluded.criterion_type,field_key=excluded.field_key,rule_json=excluded.rule_json,source_ids=excluded.source_ids,verification_state='verified',last_verified_at=now(),recheck_after=excluded.recheck_after,updated_at=now();