import { createClient } from "npm:@supabase/supabase-js@2";
const ORIGIN="https://aqoon.live";
const FORM_VERSION="phone-first-v2-multineed";
function h(){return {"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};}
function clean(v:unknown,max:number){return typeof v==="string"?v.trim().slice(0,max):"";}
function isUuid(v:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);}
function normalizeFinnishPhone(v:unknown){let raw=clean(v,40).replace(/[\s().-]/g,"");if(!raw)return "";if(raw.startsWith("00358"))raw="+358"+raw.slice(5);else if(raw.startsWith("358"))raw="+358"+raw.slice(3);if(raw.startsWith("+358")){if(!/^\+358\d+$/.test(raw))return "";let n=raw.slice(4);if(n.startsWith("0"))n=n.slice(1);if(!/^[1-9]\d{6,9}$/.test(n))return "";return "+358"+n;}if(!/^\d+$/.test(raw))return "";if(/^0\d{7,10}$/.test(raw))return "+358"+raw.slice(1);return "";}
Deno.serve(async(req)=>{const H=h();if(req.method==="OPTIONS")return new Response(null,{status:204,headers:H});if(req.method!=="POST")return new Response(JSON.stringify({error:"method_not_allowed"}),{status:405,headers:H});let b:any={};try{b=await req.json()}catch{return new Response(JSON.stringify({error:"invalid_json"}),{status:400,headers:H})}
 if(clean(b.website,50))return new Response(JSON.stringify({ok:true}),{headers:H});const name=clean(b.name,120),phone=normalizeFinnishPhone(b.phone),rid=clean(b.request_id,50),vid=clean(b.visitor_id,50),sid=clean(b.session_id,50);if(!name||!phone||!isUuid(rid)||!isUuid(vid)||!isUuid(sid))return new Response(JSON.stringify({error:"missing_or_invalid_fields"}),{status:400,headers:H});
 const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return new Response(JSON.stringify({error:"server_config"}),{status:500,headers:H});const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
 const row={request_id:rid,visitor_id:vid,session_id:sid,name,phone,form_version:FORM_VERSION,updated_at:new Date().toISOString(),referrer_host:clean(b.referrer_host,200)||null,utm_source:clean(b.utm_source,100)||null,utm_medium:clean(b.utm_medium,100)||null,utm_campaign:clean(b.utm_campaign,150)||null};
 const {data,error}=await db.from("family_intake_contacts").upsert(row,{onConflict:"request_id"}).select("id").single();if(error)return new Response(JSON.stringify({error:"db_error"}),{status:500,headers:H});
 const funnel=await db.from("family_funnel_events").insert({event_id:crypto.randomUUID(),visitor_id:vid,session_id:sid,event_name:"contact_saved",form_version:FORM_VERSION,path:"/caawi",screen:"contact",referrer_host:row.referrer_host,utm_source:row.utm_source,utm_medium:row.utm_medium,utm_campaign:row.utm_campaign,device_type:/mobi|iphone|android/i.test(req.headers.get("user-agent")||"")?"mobile":"desktop"});if(funnel.error)return new Response(JSON.stringify({error:"funnel_event_write_failed"}),{status:500,headers:H});
 return new Response(JSON.stringify({ok:true,id:data.id,phone,form_version:FORM_VERSION}),{headers:H});});
